# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bender.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BenderWindow(object):
    def setupUi(self, BenderWindow):
        BenderWindow.setObjectName(_fromUtf8("BenderWindow"))
        BenderWindow.resize(737, 694)
        self.centralwidget = QtGui.QWidget(BenderWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.fileNameLabel = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.fileNameLabel.setFont(font)
        self.fileNameLabel.setObjectName(_fromUtf8("fileNameLabel"))
        self.horizontalLayout.addWidget(self.fileNameLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.goButton = QtGui.QPushButton(self.centralwidget)
        self.goButton.setObjectName(_fromUtf8("goButton"))
        self.horizontalLayout.addWidget(self.goButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalSplitter = QtGui.QSplitter(self.centralwidget)
        self.verticalSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.verticalSplitter.setObjectName(_fromUtf8("verticalSplitter"))
        self.verticalLayoutWidget = QtGui.QWidget(self.verticalSplitter)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.nextFileNumberBox = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.nextFileNumberBox.setMinimum(1)
        self.nextFileNumberBox.setMaximum(10000)
        self.nextFileNumberBox.setProperty("value", 1)
        self.nextFileNumberBox.setObjectName(_fromUtf8("nextFileNumberBox"))
        self.gridLayout.addWidget(self.nextFileNumberBox, 6, 1, 1, 1)
        self.fileNamePatternEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.fileNamePatternEdit.setObjectName(_fromUtf8("fileNamePatternEdit"))
        self.gridLayout.addWidget(self.fileNamePatternEdit, 5, 1, 1, 4)
        self.browseOutputPathButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.browseOutputPathButton.setObjectName(_fromUtf8("browseOutputPathButton"))
        self.gridLayout.addWidget(self.browseOutputPathButton, 1, 4, 1, 1)
        self.outputPathEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.outputPathEdit.setObjectName(_fromUtf8("outputPathEdit"))
        self.gridLayout.addWidget(self.outputPathEdit, 1, 1, 1, 3)
        self.restartNumberingButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.restartNumberingButton.setObjectName(_fromUtf8("restartNumberingButton"))
        self.gridLayout.addWidget(self.restartNumberingButton, 6, 2, 1, 1)
        self.nextFileNameLabel = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextFileNameLabel.sizePolicy().hasHeightForWidth())
        self.nextFileNameLabel.setSizePolicy(sizePolicy)
        self.nextFileNameLabel.setObjectName(_fromUtf8("nextFileNameLabel"))
        self.gridLayout.addWidget(self.nextFileNameLabel, 6, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.parameterTreeWidget = ParameterTree(self.verticalLayoutWidget)
        self.parameterTreeWidget.setObjectName(_fromUtf8("parameterTreeWidget"))
        self.parameterTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout.addWidget(self.parameterTreeWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.loadParametersButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.loadParametersButton.setObjectName(_fromUtf8("loadParametersButton"))
        self.horizontalLayout_2.addWidget(self.loadParametersButton)
        self.saveParametersButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.saveParametersButton.setObjectName(_fromUtf8("saveParametersButton"))
        self.horizontalLayout_2.addWidget(self.saveParametersButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.plotSplitter = QtGui.QSplitter(self.verticalSplitter)
        self.plotSplitter.setOrientation(QtCore.Qt.Vertical)
        self.plotSplitter.setObjectName(_fromUtf8("plotSplitter"))
        self.plot1Widget = PlotWidget(self.plotSplitter)
        self.plot1Widget.setObjectName(_fromUtf8("plot1Widget"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.plotSplitter)
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.plotYBox = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.plotYBox.setObjectName(_fromUtf8("plotYBox"))
        self.plotYBox.addItem(_fromUtf8(""))
        self.plotYBox.addItem(_fromUtf8(""))
        self.plotYBox.addItem(_fromUtf8(""))
        self.plotYBox.addItem(_fromUtf8(""))
        self.plotYBox.addItem(_fromUtf8(""))
        self.plotYBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.plotYBox)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.plotXBox = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.plotXBox.setObjectName(_fromUtf8("plotXBox"))
        self.plotXBox.addItem(_fromUtf8(""))
        self.plotXBox.addItem(_fromUtf8(""))
        self.plotXBox.addItem(_fromUtf8(""))
        self.plotXBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.plotXBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.colorByBox = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.colorByBox.setObjectName(_fromUtf8("colorByBox"))
        self.colorByBox.addItem(_fromUtf8(""))
        self.colorByBox.addItem(_fromUtf8(""))
        self.colorByBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.colorByBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.overlayCheck = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.overlayCheck.setObjectName(_fromUtf8("overlayCheck"))
        self.horizontalLayout_4.addWidget(self.overlayCheck)
        self.plotYOverlayBox = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.plotYOverlayBox.setObjectName(_fromUtf8("plotYOverlayBox"))
        self.plotYOverlayBox.addItem(_fromUtf8(""))
        self.plotYOverlayBox.addItem(_fromUtf8(""))
        self.plotYOverlayBox.addItem(_fromUtf8(""))
        self.plotYOverlayBox.addItem(_fromUtf8(""))
        self.plotYOverlayBox.addItem(_fromUtf8(""))
        self.plotYOverlayBox.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.plotYOverlayBox)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.overlayFromBox = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.overlayFromBox.setObjectName(_fromUtf8("overlayFromBox"))
        self.overlayFromBox.addItem(_fromUtf8(""))
        self.overlayFromBox.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.overlayFromBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.overlayColorBox = QtGui.QComboBox(self.verticalLayoutWidget_2)
        self.overlayColorBox.setObjectName(_fromUtf8("overlayColorBox"))
        self.overlayColorBox.addItem(_fromUtf8(""))
        self.overlayColorBox.addItem(_fromUtf8(""))
        self.overlayColorBox.addItem(_fromUtf8(""))
        self.overlayColorBox.addItem(_fromUtf8(""))
        self.overlayColorBox.addItem(_fromUtf8(""))
        self.overlayColorBox.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.overlayColorBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.filterCheck = QtGui.QCheckBox(self.verticalLayoutWidget_2)
        self.filterCheck.setChecked(True)
        self.filterCheck.setObjectName(_fromUtf8("filterCheck"))
        self.horizontalLayout_5.addWidget(self.filterCheck)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.filterCutoffBox = QtGui.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.filterCutoffBox.setDecimals(0)
        self.filterCutoffBox.setMaximum(500.0)
        self.filterCutoffBox.setSingleStep(10.0)
        self.filterCutoffBox.setProperty("value", 20.0)
        self.filterCutoffBox.setObjectName(_fromUtf8("filterCutoffBox"))
        self.horizontalLayout_5.addWidget(self.filterCutoffBox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.plot2Widget = PlotWidget(self.verticalLayoutWidget_2)
        self.plot2Widget.setObjectName(_fromUtf8("plot2Widget"))
        self.verticalLayout_3.addWidget(self.plot2Widget)
        self.verticalLayout_2.addWidget(self.verticalSplitter)
        self.verticalLayout_2.setStretch(1, 100)
        BenderWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(BenderWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BenderWindow.setStatusBar(self.statusbar)

        self.retranslateUi(BenderWindow)
        QtCore.QMetaObject.connectSlotsByName(BenderWindow)

    def retranslateUi(self, BenderWindow):
        BenderWindow.setWindowTitle(_translate("BenderWindow", "Bender", None))
        self.fileNameLabel.setText(_translate("BenderWindow", "TextLabel", None))
        self.goButton.setText(_translate("BenderWindow", "Go", None))
        self.label.setText(_translate("BenderWindow", "Output path:", None))
        self.label_2.setText(_translate("BenderWindow", "File name pattern:", None))
        self.label_3.setText(_translate("BenderWindow", "Next trial:", None))
        self.fileNamePatternEdit.setToolTip(_translate("BenderWindow", "Codes:\n"
"{f}=Frequency\n"
"{a}=Amplitude", None))
        self.browseOutputPathButton.setText(_translate("BenderWindow", "Browse...", None))
        self.restartNumberingButton.setText(_translate("BenderWindow", "Restart", None))
        self.nextFileNameLabel.setText(_translate("BenderWindow", "Next file", None))
        self.loadParametersButton.setText(_translate("BenderWindow", "Load...", None))
        self.saveParametersButton.setText(_translate("BenderWindow", "Save...", None))
        self.plotYBox.setItemText(0, _translate("BenderWindow", "X torque", None))
        self.plotYBox.setItemText(1, _translate("BenderWindow", "Y force", None))
        self.plotYBox.setItemText(2, _translate("BenderWindow", "X force", None))
        self.plotYBox.setItemText(3, _translate("BenderWindow", "Y force", None))
        self.plotYBox.setItemText(4, _translate("BenderWindow", "Z force", None))
        self.plotYBox.setItemText(5, _translate("BenderWindow", "Z torque", None))
        self.label_4.setText(_translate("BenderWindow", "vs.", None))
        self.plotXBox.setItemText(0, _translate("BenderWindow", "Time (sec)", None))
        self.plotXBox.setItemText(1, _translate("BenderWindow", "Time (cycles)", None))
        self.plotXBox.setItemText(2, _translate("BenderWindow", "Phase", None))
        self.plotXBox.setItemText(3, _translate("BenderWindow", "Angle", None))
        self.label_5.setText(_translate("BenderWindow", "Color by", None))
        self.colorByBox.setItemText(0, _translate("BenderWindow", "None", None))
        self.colorByBox.setItemText(1, _translate("BenderWindow", "Active/passive", None))
        self.colorByBox.setItemText(2, _translate("BenderWindow", "Cycle number", None))
        self.overlayCheck.setText(_translate("BenderWindow", "Overlay", None))
        self.plotYOverlayBox.setItemText(0, _translate("BenderWindow", "X torque", None))
        self.plotYOverlayBox.setItemText(1, _translate("BenderWindow", "Y force", None))
        self.plotYOverlayBox.setItemText(2, _translate("BenderWindow", "X force", None))
        self.plotYOverlayBox.setItemText(3, _translate("BenderWindow", "Y force", None))
        self.plotYOverlayBox.setItemText(4, _translate("BenderWindow", "Z force", None))
        self.plotYOverlayBox.setItemText(5, _translate("BenderWindow", "Z torque", None))
        self.label_6.setText(_translate("BenderWindow", "from", None))
        self.overlayFromBox.setItemText(0, _translate("BenderWindow", "Current file", None))
        self.overlayFromBox.setItemText(1, _translate("BenderWindow", "Other file...", None))
        self.label_7.setText(_translate("BenderWindow", "Color", None))
        self.overlayColorBox.setItemText(0, _translate("BenderWindow", "Red", None))
        self.overlayColorBox.setItemText(1, _translate("BenderWindow", "Blue", None))
        self.overlayColorBox.setItemText(2, _translate("BenderWindow", "Green", None))
        self.overlayColorBox.setItemText(3, _translate("BenderWindow", "Black", None))
        self.overlayColorBox.setItemText(4, _translate("BenderWindow", "Dark red", None))
        self.overlayColorBox.setItemText(5, _translate("BenderWindow", "Dark blue", None))
        self.filterCheck.setText(_translate("BenderWindow", "Filter", None))
        self.label_8.setText(_translate("BenderWindow", "Cutoff", None))
        self.filterCutoffBox.setSuffix(_translate("BenderWindow", "Hz", None))

from pyqtgraph import PlotWidget
from pyqtgraph.parametertree import ParameterTree
