# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SetupDialog(object):
    def setupUi(self, SetupDialog):
        SetupDialog.setObjectName(_fromUtf8("SetupDialog"))
        SetupDialog.resize(644, 557)
        self.verticalLayout = QtGui.QVBoxLayout(SetupDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(SetupDialog)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.page)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_124 = QtGui.QLabel(self.page)
        self.label_124.setObjectName(_fromUtf8("label_124"))
        self.horizontalLayout_4.addWidget(self.label_124)
        self.inputFrequencyBox = QtGui.QDoubleSpinBox(self.page)
        self.inputFrequencyBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.inputFrequencyBox.setDecimals(0)
        self.inputFrequencyBox.setMaximum(100.0)
        self.inputFrequencyBox.setProperty("value", 10.0)
        self.inputFrequencyBox.setObjectName(_fromUtf8("inputFrequencyBox"))
        self.horizontalLayout_4.addWidget(self.inputFrequencyBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)
        self.yForceEdit = QtGui.QLineEdit(self.page)
        self.yForceEdit.setObjectName(_fromUtf8("yForceEdit"))
        self.gridLayout_2.addWidget(self.yForceEdit, 2, 1, 1, 1)
        self.zForceEdit = QtGui.QLineEdit(self.page)
        self.zForceEdit.setObjectName(_fromUtf8("zForceEdit"))
        self.gridLayout_2.addWidget(self.zForceEdit, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.xForceEdit = QtGui.QLineEdit(self.page)
        self.xForceEdit.setObjectName(_fromUtf8("xForceEdit"))
        self.gridLayout_2.addWidget(self.xForceEdit, 1, 1, 1, 1)
        self.xTorqueEdit = QtGui.QLineEdit(self.page)
        self.xTorqueEdit.setObjectName(_fromUtf8("xTorqueEdit"))
        self.gridLayout_2.addWidget(self.xTorqueEdit, 1, 3, 1, 1)
        self.yTorqueEdit = QtGui.QLineEdit(self.page)
        self.yTorqueEdit.setObjectName(_fromUtf8("yTorqueEdit"))
        self.gridLayout_2.addWidget(self.yTorqueEdit, 2, 3, 1, 1)
        self.zTorqueEdit = QtGui.QLineEdit(self.page)
        self.zTorqueEdit.setObjectName(_fromUtf8("zTorqueEdit"))
        self.gridLayout_2.addWidget(self.zTorqueEdit, 3, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.page)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.page)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.page)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.page)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 3, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 3, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_14 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout.addWidget(self.label_14)
        self.loadCalibrationButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadCalibrationButton.sizePolicy().hasHeightForWidth())
        self.loadCalibrationButton.setSizePolicy(sizePolicy)
        self.loadCalibrationButton.setObjectName(_fromUtf8("loadCalibrationButton"))
        self.horizontalLayout.addWidget(self.loadCalibrationButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.calibrationBox_6_2 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_6_2.sizePolicy().hasHeightForWidth())
        self.calibrationBox_6_2.setSizePolicy(sizePolicy)
        self.calibrationBox_6_2.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_6_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_6_2.setDecimals(5)
        self.calibrationBox_6_2.setMinimum(-1000.0)
        self.calibrationBox_6_2.setMaximum(1000.0)
        self.calibrationBox_6_2.setObjectName(_fromUtf8("calibrationBox_6_2"))
        self.gridLayout_3.addWidget(self.calibrationBox_6_2, 5, 5, 1, 1)
        self.calibrationBox_5_2 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_5_2.sizePolicy().hasHeightForWidth())
        self.calibrationBox_5_2.setSizePolicy(sizePolicy)
        self.calibrationBox_5_2.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_5_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_5_2.setDecimals(5)
        self.calibrationBox_5_2.setMinimum(-1000.0)
        self.calibrationBox_5_2.setMaximum(1000.0)
        self.calibrationBox_5_2.setObjectName(_fromUtf8("calibrationBox_5_2"))
        self.gridLayout_3.addWidget(self.calibrationBox_5_2, 4, 5, 1, 1)
        self.calibrationBox_4_6 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_4_6.sizePolicy().hasHeightForWidth())
        self.calibrationBox_4_6.setSizePolicy(sizePolicy)
        self.calibrationBox_4_6.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_4_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_4_6.setDecimals(5)
        self.calibrationBox_4_6.setMinimum(-1000.0)
        self.calibrationBox_4_6.setMaximum(1000.0)
        self.calibrationBox_4_6.setObjectName(_fromUtf8("calibrationBox_4_6"))
        self.gridLayout_3.addWidget(self.calibrationBox_4_6, 3, 9, 1, 1)
        self.calibrationBox_1_5 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_1_5.sizePolicy().hasHeightForWidth())
        self.calibrationBox_1_5.setSizePolicy(sizePolicy)
        self.calibrationBox_1_5.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_1_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_1_5.setDecimals(5)
        self.calibrationBox_1_5.setMinimum(-1000.0)
        self.calibrationBox_1_5.setMaximum(1000.0)
        self.calibrationBox_1_5.setObjectName(_fromUtf8("calibrationBox_1_5"))
        self.gridLayout_3.addWidget(self.calibrationBox_1_5, 0, 8, 1, 1)
        self.calibrationBox_5_5 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_5_5.sizePolicy().hasHeightForWidth())
        self.calibrationBox_5_5.setSizePolicy(sizePolicy)
        self.calibrationBox_5_5.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_5_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_5_5.setDecimals(5)
        self.calibrationBox_5_5.setMinimum(-1000.0)
        self.calibrationBox_5_5.setMaximum(1000.0)
        self.calibrationBox_5_5.setObjectName(_fromUtf8("calibrationBox_5_5"))
        self.gridLayout_3.addWidget(self.calibrationBox_5_5, 4, 8, 1, 1)
        self.calibrationBox_3_5 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_3_5.sizePolicy().hasHeightForWidth())
        self.calibrationBox_3_5.setSizePolicy(sizePolicy)
        self.calibrationBox_3_5.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_3_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_3_5.setDecimals(5)
        self.calibrationBox_3_5.setMinimum(-1000.0)
        self.calibrationBox_3_5.setMaximum(1000.0)
        self.calibrationBox_3_5.setObjectName(_fromUtf8("calibrationBox_3_5"))
        self.gridLayout_3.addWidget(self.calibrationBox_3_5, 2, 8, 1, 1)
        self.calibrationBox_4_4 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_4_4.sizePolicy().hasHeightForWidth())
        self.calibrationBox_4_4.setSizePolicy(sizePolicy)
        self.calibrationBox_4_4.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_4_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_4_4.setDecimals(5)
        self.calibrationBox_4_4.setMinimum(-1000.0)
        self.calibrationBox_4_4.setMaximum(1000.0)
        self.calibrationBox_4_4.setObjectName(_fromUtf8("calibrationBox_4_4"))
        self.gridLayout_3.addWidget(self.calibrationBox_4_4, 3, 7, 1, 1)
        self.calibrationBox_3_1 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_3_1.sizePolicy().hasHeightForWidth())
        self.calibrationBox_3_1.setSizePolicy(sizePolicy)
        self.calibrationBox_3_1.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_3_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_3_1.setDecimals(5)
        self.calibrationBox_3_1.setMinimum(-1000.0)
        self.calibrationBox_3_1.setMaximum(1000.0)
        self.calibrationBox_3_1.setObjectName(_fromUtf8("calibrationBox_3_1"))
        self.gridLayout_3.addWidget(self.calibrationBox_3_1, 2, 4, 1, 1)
        self.calibrationBox_3_2 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_3_2.sizePolicy().hasHeightForWidth())
        self.calibrationBox_3_2.setSizePolicy(sizePolicy)
        self.calibrationBox_3_2.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_3_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_3_2.setDecimals(5)
        self.calibrationBox_3_2.setMinimum(-1000.0)
        self.calibrationBox_3_2.setMaximum(1000.0)
        self.calibrationBox_3_2.setObjectName(_fromUtf8("calibrationBox_3_2"))
        self.gridLayout_3.addWidget(self.calibrationBox_3_2, 2, 5, 1, 1)
        self.calibrationBox_4_1 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_4_1.sizePolicy().hasHeightForWidth())
        self.calibrationBox_4_1.setSizePolicy(sizePolicy)
        self.calibrationBox_4_1.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_4_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_4_1.setDecimals(5)
        self.calibrationBox_4_1.setMinimum(-1000.0)
        self.calibrationBox_4_1.setMaximum(1000.0)
        self.calibrationBox_4_1.setObjectName(_fromUtf8("calibrationBox_4_1"))
        self.gridLayout_3.addWidget(self.calibrationBox_4_1, 3, 4, 1, 1)
        self.calibrationBox_4_2 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_4_2.sizePolicy().hasHeightForWidth())
        self.calibrationBox_4_2.setSizePolicy(sizePolicy)
        self.calibrationBox_4_2.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_4_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_4_2.setDecimals(5)
        self.calibrationBox_4_2.setMinimum(-1000.0)
        self.calibrationBox_4_2.setMaximum(1000.0)
        self.calibrationBox_4_2.setObjectName(_fromUtf8("calibrationBox_4_2"))
        self.gridLayout_3.addWidget(self.calibrationBox_4_2, 3, 5, 1, 1)
        self.calibrationBox_2_6 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_2_6.sizePolicy().hasHeightForWidth())
        self.calibrationBox_2_6.setSizePolicy(sizePolicy)
        self.calibrationBox_2_6.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_2_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_2_6.setDecimals(5)
        self.calibrationBox_2_6.setMinimum(-1000.0)
        self.calibrationBox_2_6.setMaximum(1000.0)
        self.calibrationBox_2_6.setObjectName(_fromUtf8("calibrationBox_2_6"))
        self.gridLayout_3.addWidget(self.calibrationBox_2_6, 1, 9, 1, 1)
        self.calibrationBox_6_6 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_6_6.sizePolicy().hasHeightForWidth())
        self.calibrationBox_6_6.setSizePolicy(sizePolicy)
        self.calibrationBox_6_6.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_6_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_6_6.setDecimals(5)
        self.calibrationBox_6_6.setMinimum(-1000.0)
        self.calibrationBox_6_6.setMaximum(1000.0)
        self.calibrationBox_6_6.setObjectName(_fromUtf8("calibrationBox_6_6"))
        self.gridLayout_3.addWidget(self.calibrationBox_6_6, 5, 9, 1, 1)
        self.calibrationBox_3_4 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_3_4.sizePolicy().hasHeightForWidth())
        self.calibrationBox_3_4.setSizePolicy(sizePolicy)
        self.calibrationBox_3_4.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_3_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_3_4.setDecimals(5)
        self.calibrationBox_3_4.setMinimum(-1000.0)
        self.calibrationBox_3_4.setMaximum(1000.0)
        self.calibrationBox_3_4.setObjectName(_fromUtf8("calibrationBox_3_4"))
        self.gridLayout_3.addWidget(self.calibrationBox_3_4, 2, 7, 1, 1)
        self.calibrationBox_6_3 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_6_3.sizePolicy().hasHeightForWidth())
        self.calibrationBox_6_3.setSizePolicy(sizePolicy)
        self.calibrationBox_6_3.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_6_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_6_3.setDecimals(5)
        self.calibrationBox_6_3.setMinimum(-1000.0)
        self.calibrationBox_6_3.setMaximum(1000.0)
        self.calibrationBox_6_3.setObjectName(_fromUtf8("calibrationBox_6_3"))
        self.gridLayout_3.addWidget(self.calibrationBox_6_3, 5, 6, 1, 1)
        self.calibrationBox_1_6 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_1_6.sizePolicy().hasHeightForWidth())
        self.calibrationBox_1_6.setSizePolicy(sizePolicy)
        self.calibrationBox_1_6.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_1_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_1_6.setDecimals(5)
        self.calibrationBox_1_6.setMinimum(-1000.0)
        self.calibrationBox_1_6.setMaximum(1000.0)
        self.calibrationBox_1_6.setObjectName(_fromUtf8("calibrationBox_1_6"))
        self.gridLayout_3.addWidget(self.calibrationBox_1_6, 0, 9, 1, 1)
        self.calibrationBox_6_4 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_6_4.sizePolicy().hasHeightForWidth())
        self.calibrationBox_6_4.setSizePolicy(sizePolicy)
        self.calibrationBox_6_4.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_6_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_6_4.setDecimals(5)
        self.calibrationBox_6_4.setMinimum(-1000.0)
        self.calibrationBox_6_4.setMaximum(1000.0)
        self.calibrationBox_6_4.setObjectName(_fromUtf8("calibrationBox_6_4"))
        self.gridLayout_3.addWidget(self.calibrationBox_6_4, 5, 7, 1, 1)
        self.calibrationBox_2_1 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_2_1.sizePolicy().hasHeightForWidth())
        self.calibrationBox_2_1.setSizePolicy(sizePolicy)
        self.calibrationBox_2_1.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_2_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_2_1.setDecimals(5)
        self.calibrationBox_2_1.setMinimum(-1000.0)
        self.calibrationBox_2_1.setMaximum(1000.0)
        self.calibrationBox_2_1.setObjectName(_fromUtf8("calibrationBox_2_1"))
        self.gridLayout_3.addWidget(self.calibrationBox_2_1, 1, 4, 1, 1)
        self.calibrationBox_2_5 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_2_5.sizePolicy().hasHeightForWidth())
        self.calibrationBox_2_5.setSizePolicy(sizePolicy)
        self.calibrationBox_2_5.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_2_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_2_5.setDecimals(5)
        self.calibrationBox_2_5.setMinimum(-1000.0)
        self.calibrationBox_2_5.setMaximum(1000.0)
        self.calibrationBox_2_5.setObjectName(_fromUtf8("calibrationBox_2_5"))
        self.gridLayout_3.addWidget(self.calibrationBox_2_5, 1, 8, 1, 1)
        self.calibrationBox_2_2 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_2_2.sizePolicy().hasHeightForWidth())
        self.calibrationBox_2_2.setSizePolicy(sizePolicy)
        self.calibrationBox_2_2.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_2_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_2_2.setDecimals(5)
        self.calibrationBox_2_2.setMinimum(-1000.0)
        self.calibrationBox_2_2.setMaximum(1000.0)
        self.calibrationBox_2_2.setObjectName(_fromUtf8("calibrationBox_2_2"))
        self.gridLayout_3.addWidget(self.calibrationBox_2_2, 1, 5, 1, 1)
        self.calibrationBox_5_6 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_5_6.sizePolicy().hasHeightForWidth())
        self.calibrationBox_5_6.setSizePolicy(sizePolicy)
        self.calibrationBox_5_6.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_5_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_5_6.setDecimals(5)
        self.calibrationBox_5_6.setMinimum(-1000.0)
        self.calibrationBox_5_6.setMaximum(1000.0)
        self.calibrationBox_5_6.setObjectName(_fromUtf8("calibrationBox_5_6"))
        self.gridLayout_3.addWidget(self.calibrationBox_5_6, 4, 9, 1, 1)
        self.calibrationBox_1_2 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_1_2.sizePolicy().hasHeightForWidth())
        self.calibrationBox_1_2.setSizePolicy(sizePolicy)
        self.calibrationBox_1_2.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_1_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_1_2.setDecimals(5)
        self.calibrationBox_1_2.setMinimum(-1000.0)
        self.calibrationBox_1_2.setMaximum(1000.0)
        self.calibrationBox_1_2.setObjectName(_fromUtf8("calibrationBox_1_2"))
        self.gridLayout_3.addWidget(self.calibrationBox_1_2, 0, 5, 1, 1)
        self.calibrationBox_5_3 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_5_3.sizePolicy().hasHeightForWidth())
        self.calibrationBox_5_3.setSizePolicy(sizePolicy)
        self.calibrationBox_5_3.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_5_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_5_3.setDecimals(5)
        self.calibrationBox_5_3.setMinimum(-1000.0)
        self.calibrationBox_5_3.setMaximum(1000.0)
        self.calibrationBox_5_3.setObjectName(_fromUtf8("calibrationBox_5_3"))
        self.gridLayout_3.addWidget(self.calibrationBox_5_3, 4, 6, 1, 1)
        self.calibrationBox_6_5 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_6_5.sizePolicy().hasHeightForWidth())
        self.calibrationBox_6_5.setSizePolicy(sizePolicy)
        self.calibrationBox_6_5.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_6_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_6_5.setDecimals(5)
        self.calibrationBox_6_5.setMinimum(-1000.0)
        self.calibrationBox_6_5.setMaximum(1000.0)
        self.calibrationBox_6_5.setObjectName(_fromUtf8("calibrationBox_6_5"))
        self.gridLayout_3.addWidget(self.calibrationBox_6_5, 5, 8, 1, 1)
        self.calibrationBox_4_3 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_4_3.sizePolicy().hasHeightForWidth())
        self.calibrationBox_4_3.setSizePolicy(sizePolicy)
        self.calibrationBox_4_3.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_4_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_4_3.setDecimals(5)
        self.calibrationBox_4_3.setMinimum(-1000.0)
        self.calibrationBox_4_3.setMaximum(1000.0)
        self.calibrationBox_4_3.setObjectName(_fromUtf8("calibrationBox_4_3"))
        self.gridLayout_3.addWidget(self.calibrationBox_4_3, 3, 6, 1, 1)
        self.calibrationBox_5_1 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_5_1.sizePolicy().hasHeightForWidth())
        self.calibrationBox_5_1.setSizePolicy(sizePolicy)
        self.calibrationBox_5_1.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_5_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_5_1.setDecimals(5)
        self.calibrationBox_5_1.setMinimum(-1000.0)
        self.calibrationBox_5_1.setMaximum(1000.0)
        self.calibrationBox_5_1.setObjectName(_fromUtf8("calibrationBox_5_1"))
        self.gridLayout_3.addWidget(self.calibrationBox_5_1, 4, 4, 1, 1)
        self.calibrationBox_6_1 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_6_1.sizePolicy().hasHeightForWidth())
        self.calibrationBox_6_1.setSizePolicy(sizePolicy)
        self.calibrationBox_6_1.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_6_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_6_1.setDecimals(5)
        self.calibrationBox_6_1.setMinimum(-1000.0)
        self.calibrationBox_6_1.setMaximum(1000.0)
        self.calibrationBox_6_1.setObjectName(_fromUtf8("calibrationBox_6_1"))
        self.gridLayout_3.addWidget(self.calibrationBox_6_1, 5, 4, 1, 1)
        self.calibrationBox_3_6 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_3_6.sizePolicy().hasHeightForWidth())
        self.calibrationBox_3_6.setSizePolicy(sizePolicy)
        self.calibrationBox_3_6.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_3_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_3_6.setDecimals(5)
        self.calibrationBox_3_6.setMinimum(-1000.0)
        self.calibrationBox_3_6.setMaximum(1000.0)
        self.calibrationBox_3_6.setObjectName(_fromUtf8("calibrationBox_3_6"))
        self.gridLayout_3.addWidget(self.calibrationBox_3_6, 2, 9, 1, 1)
        self.calibrationBox_5_4 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_5_4.sizePolicy().hasHeightForWidth())
        self.calibrationBox_5_4.setSizePolicy(sizePolicy)
        self.calibrationBox_5_4.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_5_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_5_4.setDecimals(5)
        self.calibrationBox_5_4.setMinimum(-1000.0)
        self.calibrationBox_5_4.setMaximum(1000.0)
        self.calibrationBox_5_4.setObjectName(_fromUtf8("calibrationBox_5_4"))
        self.gridLayout_3.addWidget(self.calibrationBox_5_4, 4, 7, 1, 1)
        self.calibrationBox_3_3 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_3_3.sizePolicy().hasHeightForWidth())
        self.calibrationBox_3_3.setSizePolicy(sizePolicy)
        self.calibrationBox_3_3.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_3_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_3_3.setDecimals(5)
        self.calibrationBox_3_3.setMinimum(-1000.0)
        self.calibrationBox_3_3.setMaximum(1000.0)
        self.calibrationBox_3_3.setObjectName(_fromUtf8("calibrationBox_3_3"))
        self.gridLayout_3.addWidget(self.calibrationBox_3_3, 2, 6, 1, 1)
        self.calibrationBox_1_4 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_1_4.sizePolicy().hasHeightForWidth())
        self.calibrationBox_1_4.setSizePolicy(sizePolicy)
        self.calibrationBox_1_4.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_1_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_1_4.setDecimals(5)
        self.calibrationBox_1_4.setMinimum(-1000.0)
        self.calibrationBox_1_4.setMaximum(1000.0)
        self.calibrationBox_1_4.setObjectName(_fromUtf8("calibrationBox_1_4"))
        self.gridLayout_3.addWidget(self.calibrationBox_1_4, 0, 7, 1, 1)
        self.calibrationBox_1_1 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_1_1.sizePolicy().hasHeightForWidth())
        self.calibrationBox_1_1.setSizePolicy(sizePolicy)
        self.calibrationBox_1_1.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_1_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_1_1.setDecimals(5)
        self.calibrationBox_1_1.setMinimum(-1000.0)
        self.calibrationBox_1_1.setMaximum(1000.0)
        self.calibrationBox_1_1.setObjectName(_fromUtf8("calibrationBox_1_1"))
        self.gridLayout_3.addWidget(self.calibrationBox_1_1, 0, 4, 1, 1)
        self.calibrationBox_1_3 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_1_3.sizePolicy().hasHeightForWidth())
        self.calibrationBox_1_3.setSizePolicy(sizePolicy)
        self.calibrationBox_1_3.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_1_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_1_3.setDecimals(5)
        self.calibrationBox_1_3.setMinimum(-1000.0)
        self.calibrationBox_1_3.setMaximum(1000.0)
        self.calibrationBox_1_3.setObjectName(_fromUtf8("calibrationBox_1_3"))
        self.gridLayout_3.addWidget(self.calibrationBox_1_3, 0, 6, 1, 1)
        self.calibrationBox_2_3 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_2_3.sizePolicy().hasHeightForWidth())
        self.calibrationBox_2_3.setSizePolicy(sizePolicy)
        self.calibrationBox_2_3.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_2_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_2_3.setDecimals(5)
        self.calibrationBox_2_3.setMinimum(-1000.0)
        self.calibrationBox_2_3.setMaximum(1000.0)
        self.calibrationBox_2_3.setObjectName(_fromUtf8("calibrationBox_2_3"))
        self.gridLayout_3.addWidget(self.calibrationBox_2_3, 1, 6, 1, 1)
        self.calibrationBox_2_4 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_2_4.sizePolicy().hasHeightForWidth())
        self.calibrationBox_2_4.setSizePolicy(sizePolicy)
        self.calibrationBox_2_4.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_2_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_2_4.setDecimals(5)
        self.calibrationBox_2_4.setMinimum(-1000.0)
        self.calibrationBox_2_4.setMaximum(1000.0)
        self.calibrationBox_2_4.setObjectName(_fromUtf8("calibrationBox_2_4"))
        self.gridLayout_3.addWidget(self.calibrationBox_2_4, 1, 7, 1, 1)
        self.calibrationBox_4_5 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_4_5.sizePolicy().hasHeightForWidth())
        self.calibrationBox_4_5.setSizePolicy(sizePolicy)
        self.calibrationBox_4_5.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_4_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_4_5.setDecimals(5)
        self.calibrationBox_4_5.setMinimum(-1000.0)
        self.calibrationBox_4_5.setMaximum(1000.0)
        self.calibrationBox_4_5.setObjectName(_fromUtf8("calibrationBox_4_5"))
        self.gridLayout_3.addWidget(self.calibrationBox_4_5, 3, 8, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.label_97 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_97.setFont(font)
        self.label_97.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_97.setObjectName(_fromUtf8("label_97"))
        self.verticalLayout_4.addWidget(self.label_97)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_133 = QtGui.QLabel(self.page)
        self.label_133.setObjectName(_fromUtf8("label_133"))
        self.gridLayout_6.addWidget(self.label_133, 0, 0, 1, 1)
        self.label_134 = QtGui.QLabel(self.page)
        self.label_134.setObjectName(_fromUtf8("label_134"))
        self.gridLayout_6.addWidget(self.label_134, 1, 0, 1, 1)
        self.encoderChannelEdit = QtGui.QLineEdit(self.page)
        self.encoderChannelEdit.setObjectName(_fromUtf8("encoderChannelEdit"))
        self.gridLayout_6.addWidget(self.encoderChannelEdit, 0, 1, 1, 1)
        self.countsPerRevBox = QtGui.QSpinBox(self.page)
        self.countsPerRevBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.countsPerRevBox.setMaximum(100000)
        self.countsPerRevBox.setObjectName(_fromUtf8("countsPerRevBox"))
        self.gridLayout_6.addWidget(self.countsPerRevBox, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_2 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_125 = QtGui.QLabel(self.page)
        self.label_125.setObjectName(_fromUtf8("label_125"))
        self.horizontalLayout_5.addWidget(self.label_125)
        self.outputFrequencyBox = QtGui.QDoubleSpinBox(self.page)
        self.outputFrequencyBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.outputFrequencyBox.setDecimals(0)
        self.outputFrequencyBox.setMaximum(1000.0)
        self.outputFrequencyBox.setProperty("value", 100.0)
        self.outputFrequencyBox.setObjectName(_fromUtf8("outputFrequencyBox"))
        self.horizontalLayout_5.addWidget(self.outputFrequencyBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_13 = QtGui.QLabel(self.page)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.rightStimEdit = QtGui.QLineEdit(self.page)
        self.rightStimEdit.setObjectName(_fromUtf8("rightStimEdit"))
        self.gridLayout_4.addWidget(self.rightStimEdit, 1, 1, 1, 1)
        self.leftStimEdit = QtGui.QLineEdit(self.page)
        self.leftStimEdit.setObjectName(_fromUtf8("leftStimEdit"))
        self.gridLayout_4.addWidget(self.leftStimEdit, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.page)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.digitalPortEdit = QtGui.QLineEdit(self.page)
        self.digitalPortEdit.setObjectName(_fromUtf8("digitalPortEdit"))
        self.gridLayout_4.addWidget(self.digitalPortEdit, 2, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.page)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_4.addWidget(self.label_30, 2, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.label_15 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_5.addWidget(self.label_15)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.motorMaxSpeedBox = QtGui.QDoubleSpinBox(self.page)
        self.motorMaxSpeedBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.motorMaxSpeedBox.setDecimals(0)
        self.motorMaxSpeedBox.setMaximum(100000.0)
        self.motorMaxSpeedBox.setProperty("value", 400.0)
        self.motorMaxSpeedBox.setObjectName(_fromUtf8("motorMaxSpeedBox"))
        self.gridLayout_5.addWidget(self.motorMaxSpeedBox, 2, 1, 1, 1)
        self.motorMaxPulseFreqBox = QtGui.QDoubleSpinBox(self.page)
        self.motorMaxPulseFreqBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.motorMaxPulseFreqBox.setDecimals(2)
        self.motorMaxPulseFreqBox.setMaximum(1000.0)
        self.motorMaxPulseFreqBox.setProperty("value", 5.0)
        self.motorMaxPulseFreqBox.setObjectName(_fromUtf8("motorMaxPulseFreqBox"))
        self.gridLayout_5.addWidget(self.motorMaxPulseFreqBox, 4, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.page)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 3, 0, 1, 1)
        self.motorMinPulseFreqBox = QtGui.QDoubleSpinBox(self.page)
        self.motorMinPulseFreqBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.motorMinPulseFreqBox.setDecimals(2)
        self.motorMinPulseFreqBox.setMaximum(100.0)
        self.motorMinPulseFreqBox.setProperty("value", 1.0)
        self.motorMinPulseFreqBox.setObjectName(_fromUtf8("motorMinPulseFreqBox"))
        self.gridLayout_5.addWidget(self.motorMinPulseFreqBox, 3, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.page)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 4, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.page)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 2, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_11 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_66 = QtGui.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_11.addWidget(self.label_66, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 1, 6, 1, 1)
        self.label_68 = QtGui.QLabel(self.page_3)
        self.label_68.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_68.setWordWrap(True)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_11.addWidget(self.label_68, 1, 2, 1, 2)
        self.label_71 = QtGui.QLabel(self.page_3)
        self.label_71.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_71.setWordWrap(True)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_11.addWidget(self.label_71, 5, 2, 1, 2)
        self.dinBox = QtGui.QDoubleSpinBox(self.page_3)
        self.dinBox.setDecimals(1)
        self.dinBox.setSingleStep(0.1)
        self.dinBox.setObjectName(_fromUtf8("dinBox"))
        self.gridLayout_11.addWidget(self.dinBox, 6, 3, 1, 1)
        self.doutHorizBox = QtGui.QDoubleSpinBox(self.page_3)
        self.doutHorizBox.setDecimals(1)
        self.doutHorizBox.setSingleStep(0.1)
        self.doutHorizBox.setObjectName(_fromUtf8("doutHorizBox"))
        self.gridLayout_11.addWidget(self.doutHorizBox, 4, 3, 1, 1)
        self.doutVertBox = QtGui.QDoubleSpinBox(self.page_3)
        self.doutVertBox.setDecimals(1)
        self.doutVertBox.setMaximum(1000.0)
        self.doutVertBox.setSingleStep(1.0)
        self.doutVertBox.setObjectName(_fromUtf8("doutVertBox"))
        self.gridLayout_11.addWidget(self.doutVertBox, 2, 3, 1, 1)
        self.label_119 = QtGui.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_119.setFont(font)
        self.label_119.setObjectName(_fromUtf8("label_119"))
        self.gridLayout_11.addWidget(self.label_119, 8, 2, 1, 1)
        self.label_70 = QtGui.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_70.setFont(font)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_11.addWidget(self.label_70, 4, 2, 1, 1)
        self.label_73 = QtGui.QLabel(self.page_3)
        self.label_73.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_73.setWordWrap(True)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout_11.addWidget(self.label_73, 7, 2, 1, 2)
        self.label_120 = QtGui.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_120.setFont(font)
        self.label_120.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_120.setObjectName(_fromUtf8("label_120"))
        self.gridLayout_11.addWidget(self.label_120, 0, 4, 1, 1)
        self.label_72 = QtGui.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_72.setFont(font)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_11.addWidget(self.label_72, 6, 2, 1, 1)
        self.label_67 = QtGui.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_11.addWidget(self.label_67, 2, 2, 1, 1)
        self.label_69 = QtGui.QLabel(self.page_3)
        self.label_69.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_69.setWordWrap(True)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_11.addWidget(self.label_69, 3, 2, 1, 2)
        self.dclampBox = QtGui.QDoubleSpinBox(self.page_3)
        self.dclampBox.setDecimals(1)
        self.dclampBox.setSingleStep(0.1)
        self.dclampBox.setObjectName(_fromUtf8("dclampBox"))
        self.gridLayout_11.addWidget(self.dclampBox, 8, 3, 1, 1)
        self.label_122 = QtGui.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_122.setFont(font)
        self.label_122.setObjectName(_fromUtf8("label_122"))
        self.gridLayout_11.addWidget(self.label_122, 3, 4, 1, 1)
        self.heightBox = QtGui.QDoubleSpinBox(self.page_3)
        self.heightBox.setDecimals(1)
        self.heightBox.setMaximum(1000.0)
        self.heightBox.setSingleStep(1.0)
        self.heightBox.setObjectName(_fromUtf8("heightBox"))
        self.gridLayout_11.addWidget(self.heightBox, 3, 5, 1, 1)
        self.label_121 = QtGui.QLabel(self.page_3)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_121.setFont(font)
        self.label_121.setObjectName(_fromUtf8("label_121"))
        self.gridLayout_11.addWidget(self.label_121, 2, 4, 1, 1)
        self.widthBox = QtGui.QDoubleSpinBox(self.page_3)
        self.widthBox.setDecimals(1)
        self.widthBox.setMaximum(1000.0)
        self.widthBox.setSingleStep(1.0)
        self.widthBox.setObjectName(_fromUtf8("widthBox"))
        self.gridLayout_11.addWidget(self.widthBox, 2, 5, 1, 1)
        self.label_123 = QtGui.QLabel(self.page_3)
        self.label_123.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_123.setWordWrap(True)
        self.label_123.setObjectName(_fromUtf8("label_123"))
        self.gridLayout_11.addWidget(self.label_123, 1, 4, 1, 2)
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.stimulusTypeTab = QtGui.QTabWidget(self.page_2)
        self.stimulusTypeTab.setTabPosition(QtGui.QTabWidget.North)
        self.stimulusTypeTab.setObjectName(_fromUtf8("stimulusTypeTab"))
        self.sineTab = QtGui.QWidget()
        self.sineTab.setObjectName(_fromUtf8("sineTab"))
        self.gridLayout = QtGui.QGridLayout(self.sineTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stimPulseRateBox = QtGui.QDoubleSpinBox(self.sineTab)
        self.stimPulseRateBox.setDecimals(1)
        self.stimPulseRateBox.setObjectName(_fromUtf8("stimPulseRateBox"))
        self.gridLayout.addWidget(self.stimPulseRateBox, 4, 3, 1, 2)
        self.label_24 = QtGui.QLabel(self.sineTab)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 6, 3, 1, 1)
        self.label_23 = QtGui.QLabel(self.sineTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 0, 2, 1, 3)
        self.leftVoltageScale = QtGui.QDoubleSpinBox(self.sineTab)
        self.leftVoltageScale.setDecimals(1)
        self.leftVoltageScale.setProperty("value", 1.0)
        self.leftVoltageScale.setObjectName(_fromUtf8("leftVoltageScale"))
        self.gridLayout.addWidget(self.leftVoltageScale, 7, 4, 1, 1)
        self.rightStimCheck = QtGui.QCheckBox(self.sineTab)
        self.rightStimCheck.setObjectName(_fromUtf8("rightStimCheck"))
        self.gridLayout.addWidget(self.rightStimCheck, 8, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 10, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.sineTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 0, 0, 1, 2)
        self.stimPhaseBox = QtGui.QDoubleSpinBox(self.sineTab)
        self.stimPhaseBox.setDecimals(0)
        self.stimPhaseBox.setMinimum(-100.0)
        self.stimPhaseBox.setSingleStep(5.0)
        self.stimPhaseBox.setObjectName(_fromUtf8("stimPhaseBox"))
        self.gridLayout.addWidget(self.stimPhaseBox, 2, 3, 1, 2)
        self.label_25 = QtGui.QLabel(self.sineTab)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 2, 2, 1, 1)
        self.rightVoltageBox = QtGui.QDoubleSpinBox(self.sineTab)
        self.rightVoltageBox.setDecimals(1)
        self.rightVoltageBox.setObjectName(_fromUtf8("rightVoltageBox"))
        self.gridLayout.addWidget(self.rightVoltageBox, 8, 4, 1, 1)
        self.label_27 = QtGui.QLabel(self.sineTab)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 8, 3, 1, 1)
        self.label_26 = QtGui.QLabel(self.sineTab)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 4, 2, 1, 1)
        self.leftStimCheck = QtGui.QCheckBox(self.sineTab)
        self.leftStimCheck.setObjectName(_fromUtf8("leftStimCheck"))
        self.gridLayout.addWidget(self.leftStimCheck, 6, 2, 1, 1)
        self.leftVoltageBox = QtGui.QDoubleSpinBox(self.sineTab)
        self.leftVoltageBox.setDecimals(1)
        self.leftVoltageBox.setObjectName(_fromUtf8("leftVoltageBox"))
        self.gridLayout.addWidget(self.leftVoltageBox, 6, 4, 1, 1)
        self.label_28 = QtGui.QLabel(self.sineTab)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout.addWidget(self.label_28, 7, 3, 1, 1)
        self.label_39 = QtGui.QLabel(self.sineTab)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout.addWidget(self.label_39, 9, 3, 1, 1)
        self.rightVoltageScale = QtGui.QDoubleSpinBox(self.sineTab)
        self.rightVoltageScale.setDecimals(1)
        self.rightVoltageScale.setProperty("value", 1.0)
        self.rightVoltageScale.setObjectName(_fromUtf8("rightVoltageScale"))
        self.gridLayout.addWidget(self.rightVoltageScale, 9, 4, 1, 1)
        self.actStartCycleBox = QtGui.QSpinBox(self.sineTab)
        self.actStartCycleBox.setObjectName(_fromUtf8("actStartCycleBox"))
        self.gridLayout.addWidget(self.actStartCycleBox, 1, 3, 1, 2)
        self.label_31 = QtGui.QLabel(self.sineTab)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout.addWidget(self.label_31, 1, 2, 1, 1)
        self.bendAmplitudeBox = QtGui.QDoubleSpinBox(self.sineTab)
        self.bendAmplitudeBox.setDecimals(0)
        self.bendAmplitudeBox.setObjectName(_fromUtf8("bendAmplitudeBox"))
        self.gridLayout.addWidget(self.bendAmplitudeBox, 1, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.sineTab)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.sineTab)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 2, 0, 1, 1)
        self.bendFrequencyBox = QtGui.QDoubleSpinBox(self.sineTab)
        self.bendFrequencyBox.setDecimals(2)
        self.bendFrequencyBox.setSingleStep(0.1)
        self.bendFrequencyBox.setObjectName(_fromUtf8("bendFrequencyBox"))
        self.gridLayout.addWidget(self.bendFrequencyBox, 2, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.sineTab)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 4, 0, 1, 1)
        self.bendCyclesBox = QtGui.QSpinBox(self.sineTab)
        self.bendCyclesBox.setObjectName(_fromUtf8("bendCyclesBox"))
        self.gridLayout.addWidget(self.bendCyclesBox, 4, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 8, 5, 1, 1)
        self.stimulusTypeTab.addTab(self.sineTab, _fromUtf8(""))
        self.freqSweepTab = QtGui.QWidget()
        self.freqSweepTab.setObjectName(_fromUtf8("freqSweepTab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.freqSweepTab)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_41 = QtGui.QLabel(self.freqSweepTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_8.addWidget(self.label_41, 0, 0, 1, 2)
        self.freqSweepFreqExponentBox = QtGui.QDoubleSpinBox(self.freqSweepTab)
        self.freqSweepFreqExponentBox.setSuffix(_fromUtf8(""))
        self.freqSweepFreqExponentBox.setDecimals(2)
        self.freqSweepFreqExponentBox.setMinimum(-1.0)
        self.freqSweepFreqExponentBox.setMaximum(0.0)
        self.freqSweepFreqExponentBox.setObjectName(_fromUtf8("freqSweepFreqExponentBox"))
        self.gridLayout_8.addWidget(self.freqSweepFreqExponentBox, 3, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem4, 2, 4, 1, 1)
        self.label_45 = QtGui.QLabel(self.freqSweepTab)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_8.addWidget(self.label_45, 4, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem5, 9, 0, 1, 1)
        self.label_44 = QtGui.QLabel(self.freqSweepTab)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_8.addWidget(self.label_44, 3, 0, 1, 1)
        self.label_42 = QtGui.QLabel(self.freqSweepTab)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_8.addWidget(self.label_42, 2, 0, 1, 1)
        self.freqSweepStartFreqBox = QtGui.QDoubleSpinBox(self.freqSweepTab)
        self.freqSweepStartFreqBox.setDecimals(2)
        self.freqSweepStartFreqBox.setSingleStep(0.1)
        self.freqSweepStartFreqBox.setObjectName(_fromUtf8("freqSweepStartFreqBox"))
        self.gridLayout_8.addWidget(self.freqSweepStartFreqBox, 2, 1, 1, 1)
        self.label_40 = QtGui.QLabel(self.freqSweepTab)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_8.addWidget(self.label_40, 7, 0, 1, 1)
        self.freqSweepAmplitudeBox = QtGui.QDoubleSpinBox(self.freqSweepTab)
        self.freqSweepAmplitudeBox.setDecimals(0)
        self.freqSweepAmplitudeBox.setObjectName(_fromUtf8("freqSweepAmplitudeBox"))
        self.gridLayout_8.addWidget(self.freqSweepAmplitudeBox, 2, 3, 1, 1)
        self.freqSweepTypeBox = QtGui.QComboBox(self.freqSweepTab)
        self.freqSweepTypeBox.setObjectName(_fromUtf8("freqSweepTypeBox"))
        self.freqSweepTypeBox.addItem(_fromUtf8(""))
        self.freqSweepTypeBox.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.freqSweepTypeBox, 4, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.freqSweepTab)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_8.addWidget(self.label_43, 2, 2, 1, 1)
        self.freqSweepDurationBox = QtGui.QDoubleSpinBox(self.freqSweepTab)
        self.freqSweepDurationBox.setDecimals(0)
        self.freqSweepDurationBox.setObjectName(_fromUtf8("freqSweepDurationBox"))
        self.gridLayout_8.addWidget(self.freqSweepDurationBox, 7, 1, 1, 1)
        self.label_46 = QtGui.QLabel(self.freqSweepTab)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_8.addWidget(self.label_46, 3, 2, 1, 1)
        self.freqSweepEndFreqBox = QtGui.QDoubleSpinBox(self.freqSweepTab)
        self.freqSweepEndFreqBox.setDecimals(2)
        self.freqSweepEndFreqBox.setSingleStep(0.1)
        self.freqSweepEndFreqBox.setObjectName(_fromUtf8("freqSweepEndFreqBox"))
        self.gridLayout_8.addWidget(self.freqSweepEndFreqBox, 3, 1, 1, 1)
        self.label_65 = QtGui.QLabel(self.freqSweepTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_65.setFont(font)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_8.addWidget(self.label_65, 0, 2, 1, 2)
        self.stimulusTypeTab.addTab(self.freqSweepTab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.stimulusTypeTab)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem6, 0, 2, 1, 1)
        self.waitPreBox = QtGui.QDoubleSpinBox(self.page_2)
        self.waitPreBox.setDecimals(0)
        self.waitPreBox.setObjectName(_fromUtf8("waitPreBox"))
        self.gridLayout_7.addWidget(self.waitPreBox, 0, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.page_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_7.addWidget(self.label_32, 0, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.page_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_7.addWidget(self.label_33, 1, 0, 1, 1)
        self.waitPostBox = QtGui.QDoubleSpinBox(self.page_2)
        self.waitPostBox.setDecimals(0)
        self.waitPostBox.setObjectName(_fromUtf8("waitPostBox"))
        self.gridLayout_7.addWidget(self.waitPostBox, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_7)
        self.stackedWidget.addWidget(self.page_2)
        self.page_7 = QtGui.QWidget()
        self.page_7.setObjectName(_fromUtf8("page_7"))
        self.gridLayout_27 = QtGui.QGridLayout(self.page_7)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.label_173 = QtGui.QLabel(self.page_7)
        self.label_173.setObjectName(_fromUtf8("label_173"))
        self.gridLayout_27.addWidget(self.label_173, 3, 0, 1, 1)
        self.exampleNameEdit = QtGui.QLineEdit(self.page_7)
        self.exampleNameEdit.setReadOnly(True)
        self.exampleNameEdit.setObjectName(_fromUtf8("exampleNameEdit"))
        self.gridLayout_27.addWidget(self.exampleNameEdit, 10, 1, 1, 1)
        self.outputPathBrowseButton = QtGui.QPushButton(self.page_7)
        self.outputPathBrowseButton.setObjectName(_fromUtf8("outputPathBrowseButton"))
        self.gridLayout_27.addWidget(self.outputPathBrowseButton, 1, 2, 1, 1)
        self.line = QtGui.QFrame(self.page_7)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_27.addWidget(self.line, 8, 0, 1, 3)
        self.label_176 = QtGui.QLabel(self.page_7)
        self.label_176.setObjectName(_fromUtf8("label_176"))
        self.gridLayout_27.addWidget(self.label_176, 2, 1, 1, 1)
        self.label_174 = QtGui.QLabel(self.page_7)
        self.label_174.setObjectName(_fromUtf8("label_174"))
        self.gridLayout_27.addWidget(self.label_174, 10, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_27.addItem(spacerItem7, 11, 0, 1, 1)
        self.outputPathEdit = QtGui.QLineEdit(self.page_7)
        self.outputPathEdit.setObjectName(_fromUtf8("outputPathEdit"))
        self.gridLayout_27.addWidget(self.outputPathEdit, 1, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.page_7)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_27.addWidget(self.label_29, 1, 0, 1, 1)
        self.label_175 = QtGui.QLabel(self.page_7)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_175.setFont(font)
        self.label_175.setObjectName(_fromUtf8("label_175"))
        self.gridLayout_27.addWidget(self.label_175, 0, 0, 1, 2)
        self.curFileNumberBox = QtGui.QSpinBox(self.page_7)
        self.curFileNumberBox.setMaximum(10000)
        self.curFileNumberBox.setProperty("value", 1)
        self.curFileNumberBox.setObjectName(_fromUtf8("curFileNumberBox"))
        self.gridLayout_27.addWidget(self.curFileNumberBox, 4, 1, 1, 1)
        self.fileNamePatternEdit = QtGui.QLineEdit(self.page_7)
        self.fileNamePatternEdit.setObjectName(_fromUtf8("fileNamePatternEdit"))
        self.gridLayout_27.addWidget(self.fileNamePatternEdit, 3, 1, 1, 1)
        self.label_177 = QtGui.QLabel(self.page_7)
        self.label_177.setObjectName(_fromUtf8("label_177"))
        self.gridLayout_27.addWidget(self.label_177, 4, 0, 1, 1)
        self.restartNumberingButton = QtGui.QPushButton(self.page_7)
        self.restartNumberingButton.setObjectName(_fromUtf8("restartNumberingButton"))
        self.gridLayout_27.addWidget(self.restartNumberingButton, 4, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_7)
        self.verticalLayout.addWidget(self.stackedWidget)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cancelButton = QtGui.QPushButton(SetupDialog)
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.horizontalLayout_2.addWidget(self.cancelButton)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.backButton = QtGui.QPushButton(SetupDialog)
        self.backButton.setEnabled(False)
        self.backButton.setObjectName(_fromUtf8("backButton"))
        self.horizontalLayout_2.addWidget(self.backButton)
        self.nextButton = QtGui.QPushButton(SetupDialog)
        self.nextButton.setDefault(True)
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.horizontalLayout_2.addWidget(self.nextButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_124.setBuddy(self.inputFrequencyBox)
        self.label_3.setBuddy(self.xForceEdit)
        self.label_5.setBuddy(self.xTorqueEdit)
        self.label_8.setBuddy(self.yForceEdit)
        self.label_9.setBuddy(self.zForceEdit)
        self.label_10.setBuddy(self.yTorqueEdit)
        self.label_11.setBuddy(self.zTorqueEdit)
        self.label_133.setBuddy(self.encoderChannelEdit)
        self.label_134.setBuddy(self.countsPerRevBox)
        self.label_125.setBuddy(self.outputFrequencyBox)
        self.label_13.setBuddy(self.rightStimEdit)
        self.label_12.setBuddy(self.leftStimEdit)
        self.label_30.setBuddy(self.digitalPortEdit)
        self.label_16.setBuddy(self.motorMinPulseFreqBox)
        self.label_18.setBuddy(self.motorMaxPulseFreqBox)
        self.label_17.setBuddy(self.motorMaxSpeedBox)
        self.label_119.setBuddy(self.dclampBox)
        self.label_70.setBuddy(self.doutHorizBox)
        self.label_72.setBuddy(self.dinBox)
        self.label_67.setBuddy(self.doutVertBox)
        self.label_122.setBuddy(self.heightBox)
        self.label_121.setBuddy(self.widthBox)
        self.label_24.setBuddy(self.leftVoltageBox)
        self.label_25.setBuddy(self.stimPhaseBox)
        self.label_27.setBuddy(self.rightVoltageBox)
        self.label_26.setBuddy(self.stimPulseRateBox)
        self.label_28.setBuddy(self.leftVoltageScale)
        self.label_39.setBuddy(self.rightVoltageScale)
        self.label_31.setBuddy(self.bendCyclesBox)
        self.label_19.setBuddy(self.bendAmplitudeBox)
        self.label_20.setBuddy(self.bendFrequencyBox)
        self.label_22.setBuddy(self.bendCyclesBox)
        self.label_45.setBuddy(self.freqSweepTypeBox)
        self.label_44.setBuddy(self.freqSweepEndFreqBox)
        self.label_42.setBuddy(self.freqSweepStartFreqBox)
        self.label_40.setBuddy(self.freqSweepDurationBox)
        self.label_43.setBuddy(self.freqSweepAmplitudeBox)
        self.label_46.setBuddy(self.freqSweepFreqExponentBox)
        self.label_32.setBuddy(self.bendAmplitudeBox)
        self.label_33.setBuddy(self.bendAmplitudeBox)
        self.label_173.setBuddy(self.fileNamePatternEdit)
        self.label_29.setBuddy(self.outputPathEdit)
        self.label_177.setBuddy(self.curFileNumberBox)

        self.retranslateUi(SetupDialog)
        self.stackedWidget.setCurrentIndex(2)
        self.stimulusTypeTab.setCurrentIndex(0)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), SetupDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SetupDialog)
        SetupDialog.setTabOrder(self.inputFrequencyBox, self.outputFrequencyBox)
        SetupDialog.setTabOrder(self.outputFrequencyBox, self.xForceEdit)
        SetupDialog.setTabOrder(self.xForceEdit, self.yForceEdit)
        SetupDialog.setTabOrder(self.yForceEdit, self.zForceEdit)
        SetupDialog.setTabOrder(self.zForceEdit, self.xTorqueEdit)
        SetupDialog.setTabOrder(self.xTorqueEdit, self.yTorqueEdit)
        SetupDialog.setTabOrder(self.yTorqueEdit, self.zTorqueEdit)
        SetupDialog.setTabOrder(self.zTorqueEdit, self.leftStimEdit)
        SetupDialog.setTabOrder(self.leftStimEdit, self.rightStimEdit)
        SetupDialog.setTabOrder(self.rightStimEdit, self.digitalPortEdit)
        SetupDialog.setTabOrder(self.digitalPortEdit, self.motorMaxSpeedBox)
        SetupDialog.setTabOrder(self.motorMaxSpeedBox, self.motorMinPulseFreqBox)
        SetupDialog.setTabOrder(self.motorMinPulseFreqBox, self.motorMaxPulseFreqBox)
        SetupDialog.setTabOrder(self.motorMaxPulseFreqBox, self.encoderChannelEdit)
        SetupDialog.setTabOrder(self.encoderChannelEdit, self.countsPerRevBox)
        SetupDialog.setTabOrder(self.countsPerRevBox, self.nextButton)
        SetupDialog.setTabOrder(self.nextButton, self.loadCalibrationButton)
        SetupDialog.setTabOrder(self.loadCalibrationButton, self.calibrationBox_1_1)
        SetupDialog.setTabOrder(self.calibrationBox_1_1, self.calibrationBox_1_2)
        SetupDialog.setTabOrder(self.calibrationBox_1_2, self.calibrationBox_1_3)
        SetupDialog.setTabOrder(self.calibrationBox_1_3, self.calibrationBox_1_4)
        SetupDialog.setTabOrder(self.calibrationBox_1_4, self.calibrationBox_1_5)
        SetupDialog.setTabOrder(self.calibrationBox_1_5, self.calibrationBox_1_6)
        SetupDialog.setTabOrder(self.calibrationBox_1_6, self.calibrationBox_2_1)
        SetupDialog.setTabOrder(self.calibrationBox_2_1, self.calibrationBox_2_2)
        SetupDialog.setTabOrder(self.calibrationBox_2_2, self.calibrationBox_2_3)
        SetupDialog.setTabOrder(self.calibrationBox_2_3, self.calibrationBox_2_4)
        SetupDialog.setTabOrder(self.calibrationBox_2_4, self.calibrationBox_2_5)
        SetupDialog.setTabOrder(self.calibrationBox_2_5, self.calibrationBox_2_6)
        SetupDialog.setTabOrder(self.calibrationBox_2_6, self.calibrationBox_3_1)
        SetupDialog.setTabOrder(self.calibrationBox_3_1, self.calibrationBox_3_2)
        SetupDialog.setTabOrder(self.calibrationBox_3_2, self.calibrationBox_3_3)
        SetupDialog.setTabOrder(self.calibrationBox_3_3, self.calibrationBox_3_4)
        SetupDialog.setTabOrder(self.calibrationBox_3_4, self.calibrationBox_3_5)
        SetupDialog.setTabOrder(self.calibrationBox_3_5, self.calibrationBox_3_6)
        SetupDialog.setTabOrder(self.calibrationBox_3_6, self.calibrationBox_4_1)
        SetupDialog.setTabOrder(self.calibrationBox_4_1, self.calibrationBox_4_2)
        SetupDialog.setTabOrder(self.calibrationBox_4_2, self.calibrationBox_4_3)
        SetupDialog.setTabOrder(self.calibrationBox_4_3, self.calibrationBox_4_4)
        SetupDialog.setTabOrder(self.calibrationBox_4_4, self.calibrationBox_4_5)
        SetupDialog.setTabOrder(self.calibrationBox_4_5, self.calibrationBox_4_6)
        SetupDialog.setTabOrder(self.calibrationBox_4_6, self.calibrationBox_5_1)
        SetupDialog.setTabOrder(self.calibrationBox_5_1, self.calibrationBox_5_2)
        SetupDialog.setTabOrder(self.calibrationBox_5_2, self.calibrationBox_5_3)
        SetupDialog.setTabOrder(self.calibrationBox_5_3, self.calibrationBox_5_4)
        SetupDialog.setTabOrder(self.calibrationBox_5_4, self.calibrationBox_5_5)
        SetupDialog.setTabOrder(self.calibrationBox_5_5, self.calibrationBox_5_6)
        SetupDialog.setTabOrder(self.calibrationBox_5_6, self.calibrationBox_6_1)
        SetupDialog.setTabOrder(self.calibrationBox_6_1, self.calibrationBox_6_2)
        SetupDialog.setTabOrder(self.calibrationBox_6_2, self.calibrationBox_6_3)
        SetupDialog.setTabOrder(self.calibrationBox_6_3, self.calibrationBox_6_4)
        SetupDialog.setTabOrder(self.calibrationBox_6_4, self.calibrationBox_6_5)
        SetupDialog.setTabOrder(self.calibrationBox_6_5, self.calibrationBox_6_6)
        SetupDialog.setTabOrder(self.calibrationBox_6_6, self.doutVertBox)
        SetupDialog.setTabOrder(self.doutVertBox, self.doutHorizBox)
        SetupDialog.setTabOrder(self.doutHorizBox, self.dinBox)
        SetupDialog.setTabOrder(self.dinBox, self.dclampBox)
        SetupDialog.setTabOrder(self.dclampBox, self.widthBox)
        SetupDialog.setTabOrder(self.widthBox, self.heightBox)
        SetupDialog.setTabOrder(self.heightBox, self.stimPhaseBox)
        SetupDialog.setTabOrder(self.stimPhaseBox, self.stimPulseRateBox)
        SetupDialog.setTabOrder(self.stimPulseRateBox, self.leftStimCheck)
        SetupDialog.setTabOrder(self.leftStimCheck, self.leftVoltageBox)
        SetupDialog.setTabOrder(self.leftVoltageBox, self.leftVoltageScale)
        SetupDialog.setTabOrder(self.leftVoltageScale, self.rightStimCheck)
        SetupDialog.setTabOrder(self.rightStimCheck, self.rightVoltageBox)
        SetupDialog.setTabOrder(self.rightVoltageBox, self.rightVoltageScale)
        SetupDialog.setTabOrder(self.rightVoltageScale, self.freqSweepStartFreqBox)
        SetupDialog.setTabOrder(self.freqSweepStartFreqBox, self.freqSweepEndFreqBox)
        SetupDialog.setTabOrder(self.freqSweepEndFreqBox, self.freqSweepTypeBox)
        SetupDialog.setTabOrder(self.freqSweepTypeBox, self.freqSweepDurationBox)
        SetupDialog.setTabOrder(self.freqSweepDurationBox, self.freqSweepAmplitudeBox)
        SetupDialog.setTabOrder(self.freqSweepAmplitudeBox, self.freqSweepFreqExponentBox)
        SetupDialog.setTabOrder(self.freqSweepFreqExponentBox, self.outputPathEdit)
        SetupDialog.setTabOrder(self.outputPathEdit, self.outputPathBrowseButton)
        SetupDialog.setTabOrder(self.outputPathBrowseButton, self.fileNamePatternEdit)
        SetupDialog.setTabOrder(self.fileNamePatternEdit, self.curFileNumberBox)
        SetupDialog.setTabOrder(self.curFileNumberBox, self.restartNumberingButton)
        SetupDialog.setTabOrder(self.restartNumberingButton, self.exampleNameEdit)
        SetupDialog.setTabOrder(self.exampleNameEdit, self.backButton)
        SetupDialog.setTabOrder(self.backButton, self.cancelButton)
        SetupDialog.setTabOrder(self.cancelButton, self.stimulusTypeTab)

    def retranslateUi(self, SetupDialog):
        SetupDialog.setWindowTitle(_translate("SetupDialog", "Setup channels...", None))
        self.label.setText(_translate("SetupDialog", "Input channels:", None))
        self.label_124.setText(_translate("SetupDialog", "Sampling frequency:", None))
        self.inputFrequencyBox.setSuffix(_translate("SetupDialog", "kHz", None))
        self.label_3.setText(_translate("SetupDialog", "X:", None))
        self.label_5.setText(_translate("SetupDialog", "X:", None))
        self.label_7.setText(_translate("SetupDialog", "Force", None))
        self.xForceEdit.setText(_translate("SetupDialog", "Dev1/ai0", None))
        self.label_8.setText(_translate("SetupDialog", "Y:", None))
        self.label_9.setText(_translate("SetupDialog", "Z:", None))
        self.label_10.setText(_translate("SetupDialog", "Y:", None))
        self.label_11.setText(_translate("SetupDialog", "Z:", None))
        self.label_6.setText(_translate("SetupDialog", "Torque", None))
        self.label_14.setText(_translate("SetupDialog", "Calibration matrix:", None))
        self.loadCalibrationButton.setText(_translate("SetupDialog", "Load...", None))
        self.label_97.setText(_translate("SetupDialog", "Encoder input:", None))
        self.label_133.setText(_translate("SetupDialog", "Counter channel:", None))
        self.label_134.setText(_translate("SetupDialog", "Counts per revolution:", None))
        self.label_2.setText(_translate("SetupDialog", "Output channels:", None))
        self.label_125.setText(_translate("SetupDialog", "Sampling frequency:", None))
        self.outputFrequencyBox.setSuffix(_translate("SetupDialog", "kHz", None))
        self.label_13.setText(_translate("SetupDialog", "Right stim:", None))
        self.label_12.setText(_translate("SetupDialog", "Left stim:", None))
        self.label_30.setText(_translate("SetupDialog", "Digital port:", None))
        self.label_15.setText(_translate("SetupDialog", "Motor parameters:", None))
        self.motorMaxSpeedBox.setSuffix(_translate("SetupDialog", "RPM", None))
        self.motorMaxPulseFreqBox.setSuffix(_translate("SetupDialog", "kHz", None))
        self.label_16.setText(_translate("SetupDialog", "Min pulse frequency:", None))
        self.motorMinPulseFreqBox.setSuffix(_translate("SetupDialog", "kHz", None))
        self.label_18.setText(_translate("SetupDialog", "Max pulse frequency:", None))
        self.label_17.setText(_translate("SetupDialog", "Maximum speed:", None))
        self.label_66.setText(_translate("SetupDialog", "Geometry:", None))
        self.label_68.setText(_translate("SetupDialog", "Vertical distance from transducer to center of pressure", None))
        self.label_71.setText(_translate("SetupDialog", "Horizontal distance from center of pressure to center of rotation", None))
        self.dinBox.setSuffix(_translate("SetupDialog", "mm", None))
        self.doutHorizBox.setSuffix(_translate("SetupDialog", "mm", None))
        self.doutVertBox.setSuffix(_translate("SetupDialog", "mm", None))
        self.label_119.setText(_translate("SetupDialog", "d clamp", None))
        self.label_70.setText(_translate("SetupDialog", "d out, horiz", None))
        self.label_73.setText(_translate("SetupDialog", "Horizontal distance between the edges of the clamps", None))
        self.label_120.setText(_translate("SetupDialog", "Cross-section:", None))
        self.label_72.setText(_translate("SetupDialog", "d in", None))
        self.label_67.setText(_translate("SetupDialog", "d out, vert", None))
        self.label_69.setText(_translate("SetupDialog", "Horizontal distance from transducer to center of pressure", None))
        self.dclampBox.setSuffix(_translate("SetupDialog", "mm", None))
        self.label_122.setText(_translate("SetupDialog", "height", None))
        self.heightBox.setSuffix(_translate("SetupDialog", "mm", None))
        self.label_121.setText(_translate("SetupDialog", "width", None))
        self.widthBox.setSuffix(_translate("SetupDialog", "mm", None))
        self.label_123.setText(_translate("SetupDialog", "Measure body cross-section at the midpoint of the bending region", None))
        self.label_4.setText(_translate("SetupDialog", "Stimulus type:", None))
        self.stimPulseRateBox.setSuffix(_translate("SetupDialog", "Hz", None))
        self.label_24.setText(_translate("SetupDialog", "Voltage:", None))
        self.label_23.setText(_translate("SetupDialog", "Stimulation", None))
        self.leftVoltageScale.setSuffix(_translate("SetupDialog", "V/V", None))
        self.rightStimCheck.setText(_translate("SetupDialog", "Right side", None))
        self.label_21.setText(_translate("SetupDialog", "Bending", None))
        self.stimPhaseBox.setSuffix(_translate("SetupDialog", "%", None))
        self.label_25.setText(_translate("SetupDialog", "Phase:", None))
        self.rightVoltageBox.setSuffix(_translate("SetupDialog", "V", None))
        self.label_27.setText(_translate("SetupDialog", "Voltage:", None))
        self.label_26.setText(_translate("SetupDialog", "Pulse rate:", None))
        self.leftStimCheck.setText(_translate("SetupDialog", "Left side", None))
        self.leftVoltageBox.setSuffix(_translate("SetupDialog", "V", None))
        self.label_28.setText(_translate("SetupDialog", "Scale:", None))
        self.label_39.setText(_translate("SetupDialog", "Scale:", None))
        self.rightVoltageScale.setSuffix(_translate("SetupDialog", "V/V", None))
        self.label_31.setText(_translate("SetupDialog", "Start cycle:", None))
        self.bendAmplitudeBox.setSuffix(_translate("SetupDialog", "deg", None))
        self.label_19.setText(_translate("SetupDialog", "Amplitude:", None))
        self.label_20.setText(_translate("SetupDialog", "Frequency:", None))
        self.bendFrequencyBox.setSuffix(_translate("SetupDialog", "Hz", None))
        self.label_22.setText(_translate("SetupDialog", "Cycles:", None))
        self.stimulusTypeTab.setTabText(self.stimulusTypeTab.indexOf(self.sineTab), _translate("SetupDialog", "Sine", None))
        self.label_41.setText(_translate("SetupDialog", "Frequencies", None))
        self.label_45.setText(_translate("SetupDialog", "Frequency change:", None))
        self.label_44.setText(_translate("SetupDialog", "End frequency:", None))
        self.label_42.setText(_translate("SetupDialog", "Start frequency:", None))
        self.freqSweepStartFreqBox.setSuffix(_translate("SetupDialog", "Hz", None))
        self.label_40.setText(_translate("SetupDialog", "Duration:", None))
        self.freqSweepAmplitudeBox.setSuffix(_translate("SetupDialog", "deg", None))
        self.freqSweepTypeBox.setItemText(0, _translate("SetupDialog", "Exponential", None))
        self.freqSweepTypeBox.setItemText(1, _translate("SetupDialog", "Linear", None))
        self.label_43.setText(_translate("SetupDialog", "Amplitude:", None))
        self.freqSweepDurationBox.setSuffix(_translate("SetupDialog", "sec", None))
        self.label_46.setText(_translate("SetupDialog", "Frequency exponent:", None))
        self.freqSweepEndFreqBox.setSuffix(_translate("SetupDialog", "Hz", None))
        self.label_65.setText(_translate("SetupDialog", "Amplitude", None))
        self.stimulusTypeTab.setTabText(self.stimulusTypeTab.indexOf(self.freqSweepTab), _translate("SetupDialog", "Frequency Sweep", None))
        self.waitPreBox.setSuffix(_translate("SetupDialog", "sec", None))
        self.label_32.setText(_translate("SetupDialog", "Wait before:", None))
        self.label_33.setText(_translate("SetupDialog", "Wait after:", None))
        self.waitPostBox.setSuffix(_translate("SetupDialog", "sec", None))
        self.label_173.setText(_translate("SetupDialog", "File name pattern:", None))
        self.outputPathBrowseButton.setText(_translate("SetupDialog", "Browse...", None))
        self.label_176.setText(_translate("SetupDialog", "Codes:\n"
"{f} = Frequency\n"
"{a} = Amplitude\n"
"{ph} = Phase in percent\n"
"{lv} = left side voltage\n"
"{rv} = right side voltage\n"
"{f0} = Start frequency\n"
"{f1} = End frequency\n"
"{num} = File number", None))
        self.label_174.setText(_translate("SetupDialog", "Example name:", None))
        self.label_29.setText(_translate("SetupDialog", "Output path:", None))
        self.label_175.setText(_translate("SetupDialog", "Output file:", None))
        self.label_177.setText(_translate("SetupDialog", "Current number:", None))
        self.restartNumberingButton.setText(_translate("SetupDialog", "Restart", None))
        self.cancelButton.setText(_translate("SetupDialog", "Cancel", None))
        self.backButton.setText(_translate("SetupDialog", "Back", None))
        self.nextButton.setText(_translate("SetupDialog", "Next", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SetupDialog = QtGui.QDialog()
    ui = Ui_SetupDialog()
    ui.setupUi(SetupDialog)
    SetupDialog.show()
    sys.exit(app.exec_())

