# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SetupDialog(object):
    def setupUi(self, SetupDialog):
        SetupDialog.setObjectName(_fromUtf8("SetupDialog"))
        SetupDialog.resize(644, 437)
        self.verticalLayout = QtGui.QVBoxLayout(SetupDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stackedWidget = QtGui.QStackedWidget(SetupDialog)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.calibrationBox_3_6 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_3_6.sizePolicy().hasHeightForWidth())
        self.calibrationBox_3_6.setSizePolicy(sizePolicy)
        self.calibrationBox_3_6.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_3_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_3_6.setDecimals(5)
        self.calibrationBox_3_6.setMinimum(-1000.0)
        self.calibrationBox_3_6.setMaximum(1000.0)
        self.calibrationBox_3_6.setObjectName(_fromUtf8("calibrationBox_3_6"))
        self.gridLayout_3.addWidget(self.calibrationBox_3_6, 2, 9, 1, 1)
        self.calibrationBox_5_4 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_5_4.sizePolicy().hasHeightForWidth())
        self.calibrationBox_5_4.setSizePolicy(sizePolicy)
        self.calibrationBox_5_4.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_5_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_5_4.setDecimals(5)
        self.calibrationBox_5_4.setMinimum(-1000.0)
        self.calibrationBox_5_4.setMaximum(1000.0)
        self.calibrationBox_5_4.setObjectName(_fromUtf8("calibrationBox_5_4"))
        self.gridLayout_3.addWidget(self.calibrationBox_5_4, 4, 7, 1, 1)
        self.calibrationBox_3_3 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_3_3.sizePolicy().hasHeightForWidth())
        self.calibrationBox_3_3.setSizePolicy(sizePolicy)
        self.calibrationBox_3_3.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_3_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_3_3.setDecimals(5)
        self.calibrationBox_3_3.setMinimum(-1000.0)
        self.calibrationBox_3_3.setMaximum(1000.0)
        self.calibrationBox_3_3.setObjectName(_fromUtf8("calibrationBox_3_3"))
        self.gridLayout_3.addWidget(self.calibrationBox_3_3, 2, 6, 1, 1)
        self.calibrationBox_1_4 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_1_4.sizePolicy().hasHeightForWidth())
        self.calibrationBox_1_4.setSizePolicy(sizePolicy)
        self.calibrationBox_1_4.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_1_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_1_4.setDecimals(5)
        self.calibrationBox_1_4.setMinimum(-1000.0)
        self.calibrationBox_1_4.setMaximum(1000.0)
        self.calibrationBox_1_4.setObjectName(_fromUtf8("calibrationBox_1_4"))
        self.gridLayout_3.addWidget(self.calibrationBox_1_4, 0, 7, 1, 1)
        self.calibrationBox_1_1 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_1_1.sizePolicy().hasHeightForWidth())
        self.calibrationBox_1_1.setSizePolicy(sizePolicy)
        self.calibrationBox_1_1.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_1_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_1_1.setDecimals(5)
        self.calibrationBox_1_1.setMinimum(-1000.0)
        self.calibrationBox_1_1.setMaximum(1000.0)
        self.calibrationBox_1_1.setObjectName(_fromUtf8("calibrationBox_1_1"))
        self.gridLayout_3.addWidget(self.calibrationBox_1_1, 0, 4, 1, 1)
        self.calibrationBox_1_3 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_1_3.sizePolicy().hasHeightForWidth())
        self.calibrationBox_1_3.setSizePolicy(sizePolicy)
        self.calibrationBox_1_3.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_1_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_1_3.setDecimals(5)
        self.calibrationBox_1_3.setMinimum(-1000.0)
        self.calibrationBox_1_3.setMaximum(1000.0)
        self.calibrationBox_1_3.setObjectName(_fromUtf8("calibrationBox_1_3"))
        self.gridLayout_3.addWidget(self.calibrationBox_1_3, 0, 6, 1, 1)
        self.calibrationBox_2_4 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_2_4.sizePolicy().hasHeightForWidth())
        self.calibrationBox_2_4.setSizePolicy(sizePolicy)
        self.calibrationBox_2_4.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_2_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_2_4.setDecimals(5)
        self.calibrationBox_2_4.setMinimum(-1000.0)
        self.calibrationBox_2_4.setMaximum(1000.0)
        self.calibrationBox_2_4.setObjectName(_fromUtf8("calibrationBox_2_4"))
        self.gridLayout_3.addWidget(self.calibrationBox_2_4, 1, 7, 1, 1)
        self.calibrationBox_2_3 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_2_3.sizePolicy().hasHeightForWidth())
        self.calibrationBox_2_3.setSizePolicy(sizePolicy)
        self.calibrationBox_2_3.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_2_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_2_3.setDecimals(5)
        self.calibrationBox_2_3.setMinimum(-1000.0)
        self.calibrationBox_2_3.setMaximum(1000.0)
        self.calibrationBox_2_3.setObjectName(_fromUtf8("calibrationBox_2_3"))
        self.gridLayout_3.addWidget(self.calibrationBox_2_3, 1, 6, 1, 1)
        self.calibrationBox_4_5 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_4_5.sizePolicy().hasHeightForWidth())
        self.calibrationBox_4_5.setSizePolicy(sizePolicy)
        self.calibrationBox_4_5.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_4_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_4_5.setDecimals(5)
        self.calibrationBox_4_5.setMinimum(-1000.0)
        self.calibrationBox_4_5.setMaximum(1000.0)
        self.calibrationBox_4_5.setObjectName(_fromUtf8("calibrationBox_4_5"))
        self.gridLayout_3.addWidget(self.calibrationBox_4_5, 3, 8, 1, 1)
        self.calibrationBox_1_5 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_1_5.sizePolicy().hasHeightForWidth())
        self.calibrationBox_1_5.setSizePolicy(sizePolicy)
        self.calibrationBox_1_5.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_1_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_1_5.setDecimals(5)
        self.calibrationBox_1_5.setMinimum(-1000.0)
        self.calibrationBox_1_5.setMaximum(1000.0)
        self.calibrationBox_1_5.setObjectName(_fromUtf8("calibrationBox_1_5"))
        self.gridLayout_3.addWidget(self.calibrationBox_1_5, 0, 8, 1, 1)
        self.calibrationBox_4_6 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_4_6.sizePolicy().hasHeightForWidth())
        self.calibrationBox_4_6.setSizePolicy(sizePolicy)
        self.calibrationBox_4_6.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_4_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_4_6.setDecimals(5)
        self.calibrationBox_4_6.setMinimum(-1000.0)
        self.calibrationBox_4_6.setMaximum(1000.0)
        self.calibrationBox_4_6.setObjectName(_fromUtf8("calibrationBox_4_6"))
        self.gridLayout_3.addWidget(self.calibrationBox_4_6, 3, 9, 1, 1)
        self.calibrationBox_5_2 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_5_2.sizePolicy().hasHeightForWidth())
        self.calibrationBox_5_2.setSizePolicy(sizePolicy)
        self.calibrationBox_5_2.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_5_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_5_2.setDecimals(5)
        self.calibrationBox_5_2.setMinimum(-1000.0)
        self.calibrationBox_5_2.setMaximum(1000.0)
        self.calibrationBox_5_2.setObjectName(_fromUtf8("calibrationBox_5_2"))
        self.gridLayout_3.addWidget(self.calibrationBox_5_2, 4, 5, 1, 1)
        self.calibrationBox_6_2 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_6_2.sizePolicy().hasHeightForWidth())
        self.calibrationBox_6_2.setSizePolicy(sizePolicy)
        self.calibrationBox_6_2.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_6_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_6_2.setDecimals(5)
        self.calibrationBox_6_2.setMinimum(-1000.0)
        self.calibrationBox_6_2.setMaximum(1000.0)
        self.calibrationBox_6_2.setObjectName(_fromUtf8("calibrationBox_6_2"))
        self.gridLayout_3.addWidget(self.calibrationBox_6_2, 5, 5, 1, 1)
        self.calibrationBox_5_5 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_5_5.sizePolicy().hasHeightForWidth())
        self.calibrationBox_5_5.setSizePolicy(sizePolicy)
        self.calibrationBox_5_5.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_5_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_5_5.setDecimals(5)
        self.calibrationBox_5_5.setMinimum(-1000.0)
        self.calibrationBox_5_5.setMaximum(1000.0)
        self.calibrationBox_5_5.setObjectName(_fromUtf8("calibrationBox_5_5"))
        self.gridLayout_3.addWidget(self.calibrationBox_5_5, 4, 8, 1, 1)
        self.calibrationBox_4_4 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_4_4.sizePolicy().hasHeightForWidth())
        self.calibrationBox_4_4.setSizePolicy(sizePolicy)
        self.calibrationBox_4_4.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_4_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_4_4.setDecimals(5)
        self.calibrationBox_4_4.setMinimum(-1000.0)
        self.calibrationBox_4_4.setMaximum(1000.0)
        self.calibrationBox_4_4.setObjectName(_fromUtf8("calibrationBox_4_4"))
        self.gridLayout_3.addWidget(self.calibrationBox_4_4, 3, 7, 1, 1)
        self.calibrationBox_3_5 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_3_5.sizePolicy().hasHeightForWidth())
        self.calibrationBox_3_5.setSizePolicy(sizePolicy)
        self.calibrationBox_3_5.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_3_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_3_5.setDecimals(5)
        self.calibrationBox_3_5.setMinimum(-1000.0)
        self.calibrationBox_3_5.setMaximum(1000.0)
        self.calibrationBox_3_5.setObjectName(_fromUtf8("calibrationBox_3_5"))
        self.gridLayout_3.addWidget(self.calibrationBox_3_5, 2, 8, 1, 1)
        self.calibrationBox_3_1 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_3_1.sizePolicy().hasHeightForWidth())
        self.calibrationBox_3_1.setSizePolicy(sizePolicy)
        self.calibrationBox_3_1.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_3_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_3_1.setDecimals(5)
        self.calibrationBox_3_1.setMinimum(-1000.0)
        self.calibrationBox_3_1.setMaximum(1000.0)
        self.calibrationBox_3_1.setObjectName(_fromUtf8("calibrationBox_3_1"))
        self.gridLayout_3.addWidget(self.calibrationBox_3_1, 2, 4, 1, 1)
        self.calibrationBox_3_2 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_3_2.sizePolicy().hasHeightForWidth())
        self.calibrationBox_3_2.setSizePolicy(sizePolicy)
        self.calibrationBox_3_2.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_3_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_3_2.setDecimals(5)
        self.calibrationBox_3_2.setMinimum(-1000.0)
        self.calibrationBox_3_2.setMaximum(1000.0)
        self.calibrationBox_3_2.setObjectName(_fromUtf8("calibrationBox_3_2"))
        self.gridLayout_3.addWidget(self.calibrationBox_3_2, 2, 5, 1, 1)
        self.calibrationBox_4_1 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_4_1.sizePolicy().hasHeightForWidth())
        self.calibrationBox_4_1.setSizePolicy(sizePolicy)
        self.calibrationBox_4_1.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_4_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_4_1.setDecimals(5)
        self.calibrationBox_4_1.setMinimum(-1000.0)
        self.calibrationBox_4_1.setMaximum(1000.0)
        self.calibrationBox_4_1.setObjectName(_fromUtf8("calibrationBox_4_1"))
        self.gridLayout_3.addWidget(self.calibrationBox_4_1, 3, 4, 1, 1)
        self.calibrationBox_4_2 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_4_2.sizePolicy().hasHeightForWidth())
        self.calibrationBox_4_2.setSizePolicy(sizePolicy)
        self.calibrationBox_4_2.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_4_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_4_2.setDecimals(5)
        self.calibrationBox_4_2.setMinimum(-1000.0)
        self.calibrationBox_4_2.setMaximum(1000.0)
        self.calibrationBox_4_2.setObjectName(_fromUtf8("calibrationBox_4_2"))
        self.gridLayout_3.addWidget(self.calibrationBox_4_2, 3, 5, 1, 1)
        self.calibrationBox_2_6 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_2_6.sizePolicy().hasHeightForWidth())
        self.calibrationBox_2_6.setSizePolicy(sizePolicy)
        self.calibrationBox_2_6.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_2_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_2_6.setDecimals(5)
        self.calibrationBox_2_6.setMinimum(-1000.0)
        self.calibrationBox_2_6.setMaximum(1000.0)
        self.calibrationBox_2_6.setObjectName(_fromUtf8("calibrationBox_2_6"))
        self.gridLayout_3.addWidget(self.calibrationBox_2_6, 1, 9, 1, 1)
        self.calibrationBox_6_6 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_6_6.sizePolicy().hasHeightForWidth())
        self.calibrationBox_6_6.setSizePolicy(sizePolicy)
        self.calibrationBox_6_6.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_6_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_6_6.setDecimals(5)
        self.calibrationBox_6_6.setMinimum(-1000.0)
        self.calibrationBox_6_6.setMaximum(1000.0)
        self.calibrationBox_6_6.setObjectName(_fromUtf8("calibrationBox_6_6"))
        self.gridLayout_3.addWidget(self.calibrationBox_6_6, 5, 9, 1, 1)
        self.calibrationBox_3_4 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_3_4.sizePolicy().hasHeightForWidth())
        self.calibrationBox_3_4.setSizePolicy(sizePolicy)
        self.calibrationBox_3_4.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_3_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_3_4.setDecimals(5)
        self.calibrationBox_3_4.setMinimum(-1000.0)
        self.calibrationBox_3_4.setMaximum(1000.0)
        self.calibrationBox_3_4.setObjectName(_fromUtf8("calibrationBox_3_4"))
        self.gridLayout_3.addWidget(self.calibrationBox_3_4, 2, 7, 1, 1)
        self.calibrationBox_6_3 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_6_3.sizePolicy().hasHeightForWidth())
        self.calibrationBox_6_3.setSizePolicy(sizePolicy)
        self.calibrationBox_6_3.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_6_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_6_3.setDecimals(5)
        self.calibrationBox_6_3.setMinimum(-1000.0)
        self.calibrationBox_6_3.setMaximum(1000.0)
        self.calibrationBox_6_3.setObjectName(_fromUtf8("calibrationBox_6_3"))
        self.gridLayout_3.addWidget(self.calibrationBox_6_3, 5, 6, 1, 1)
        self.calibrationBox_1_6 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_1_6.sizePolicy().hasHeightForWidth())
        self.calibrationBox_1_6.setSizePolicy(sizePolicy)
        self.calibrationBox_1_6.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_1_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_1_6.setDecimals(5)
        self.calibrationBox_1_6.setMinimum(-1000.0)
        self.calibrationBox_1_6.setMaximum(1000.0)
        self.calibrationBox_1_6.setObjectName(_fromUtf8("calibrationBox_1_6"))
        self.gridLayout_3.addWidget(self.calibrationBox_1_6, 0, 9, 1, 1)
        self.calibrationBox_6_4 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_6_4.sizePolicy().hasHeightForWidth())
        self.calibrationBox_6_4.setSizePolicy(sizePolicy)
        self.calibrationBox_6_4.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_6_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_6_4.setDecimals(5)
        self.calibrationBox_6_4.setMinimum(-1000.0)
        self.calibrationBox_6_4.setMaximum(1000.0)
        self.calibrationBox_6_4.setObjectName(_fromUtf8("calibrationBox_6_4"))
        self.gridLayout_3.addWidget(self.calibrationBox_6_4, 5, 7, 1, 1)
        self.calibrationBox_2_1 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_2_1.sizePolicy().hasHeightForWidth())
        self.calibrationBox_2_1.setSizePolicy(sizePolicy)
        self.calibrationBox_2_1.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_2_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_2_1.setDecimals(5)
        self.calibrationBox_2_1.setMinimum(-1000.0)
        self.calibrationBox_2_1.setMaximum(1000.0)
        self.calibrationBox_2_1.setObjectName(_fromUtf8("calibrationBox_2_1"))
        self.gridLayout_3.addWidget(self.calibrationBox_2_1, 1, 4, 1, 1)
        self.calibrationBox_2_5 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_2_5.sizePolicy().hasHeightForWidth())
        self.calibrationBox_2_5.setSizePolicy(sizePolicy)
        self.calibrationBox_2_5.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_2_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_2_5.setDecimals(5)
        self.calibrationBox_2_5.setMinimum(-1000.0)
        self.calibrationBox_2_5.setMaximum(1000.0)
        self.calibrationBox_2_5.setObjectName(_fromUtf8("calibrationBox_2_5"))
        self.gridLayout_3.addWidget(self.calibrationBox_2_5, 1, 8, 1, 1)
        self.calibrationBox_2_2 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_2_2.sizePolicy().hasHeightForWidth())
        self.calibrationBox_2_2.setSizePolicy(sizePolicy)
        self.calibrationBox_2_2.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_2_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_2_2.setDecimals(5)
        self.calibrationBox_2_2.setMinimum(-1000.0)
        self.calibrationBox_2_2.setMaximum(1000.0)
        self.calibrationBox_2_2.setObjectName(_fromUtf8("calibrationBox_2_2"))
        self.gridLayout_3.addWidget(self.calibrationBox_2_2, 1, 5, 1, 1)
        self.calibrationBox_5_6 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_5_6.sizePolicy().hasHeightForWidth())
        self.calibrationBox_5_6.setSizePolicy(sizePolicy)
        self.calibrationBox_5_6.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_5_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_5_6.setDecimals(5)
        self.calibrationBox_5_6.setMinimum(-1000.0)
        self.calibrationBox_5_6.setMaximum(1000.0)
        self.calibrationBox_5_6.setObjectName(_fromUtf8("calibrationBox_5_6"))
        self.gridLayout_3.addWidget(self.calibrationBox_5_6, 4, 9, 1, 1)
        self.calibrationBox_5_3 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_5_3.sizePolicy().hasHeightForWidth())
        self.calibrationBox_5_3.setSizePolicy(sizePolicy)
        self.calibrationBox_5_3.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_5_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_5_3.setDecimals(5)
        self.calibrationBox_5_3.setMinimum(-1000.0)
        self.calibrationBox_5_3.setMaximum(1000.0)
        self.calibrationBox_5_3.setObjectName(_fromUtf8("calibrationBox_5_3"))
        self.gridLayout_3.addWidget(self.calibrationBox_5_3, 4, 6, 1, 1)
        self.calibrationBox_1_2 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_1_2.sizePolicy().hasHeightForWidth())
        self.calibrationBox_1_2.setSizePolicy(sizePolicy)
        self.calibrationBox_1_2.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_1_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_1_2.setDecimals(5)
        self.calibrationBox_1_2.setMinimum(-1000.0)
        self.calibrationBox_1_2.setMaximum(1000.0)
        self.calibrationBox_1_2.setObjectName(_fromUtf8("calibrationBox_1_2"))
        self.gridLayout_3.addWidget(self.calibrationBox_1_2, 0, 5, 1, 1)
        self.calibrationBox_6_5 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_6_5.sizePolicy().hasHeightForWidth())
        self.calibrationBox_6_5.setSizePolicy(sizePolicy)
        self.calibrationBox_6_5.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_6_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_6_5.setDecimals(5)
        self.calibrationBox_6_5.setMinimum(-1000.0)
        self.calibrationBox_6_5.setMaximum(1000.0)
        self.calibrationBox_6_5.setObjectName(_fromUtf8("calibrationBox_6_5"))
        self.gridLayout_3.addWidget(self.calibrationBox_6_5, 5, 8, 1, 1)
        self.calibrationBox_4_3 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_4_3.sizePolicy().hasHeightForWidth())
        self.calibrationBox_4_3.setSizePolicy(sizePolicy)
        self.calibrationBox_4_3.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_4_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_4_3.setDecimals(5)
        self.calibrationBox_4_3.setMinimum(-1000.0)
        self.calibrationBox_4_3.setMaximum(1000.0)
        self.calibrationBox_4_3.setObjectName(_fromUtf8("calibrationBox_4_3"))
        self.gridLayout_3.addWidget(self.calibrationBox_4_3, 3, 6, 1, 1)
        self.calibrationBox_5_1 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_5_1.sizePolicy().hasHeightForWidth())
        self.calibrationBox_5_1.setSizePolicy(sizePolicy)
        self.calibrationBox_5_1.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_5_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_5_1.setDecimals(5)
        self.calibrationBox_5_1.setMinimum(-1000.0)
        self.calibrationBox_5_1.setMaximum(1000.0)
        self.calibrationBox_5_1.setObjectName(_fromUtf8("calibrationBox_5_1"))
        self.gridLayout_3.addWidget(self.calibrationBox_5_1, 4, 4, 1, 1)
        self.calibrationBox_6_1 = QtGui.QDoubleSpinBox(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrationBox_6_1.sizePolicy().hasHeightForWidth())
        self.calibrationBox_6_1.setSizePolicy(sizePolicy)
        self.calibrationBox_6_1.setMinimumSize(QtCore.QSize(60, 0))
        self.calibrationBox_6_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.calibrationBox_6_1.setDecimals(5)
        self.calibrationBox_6_1.setMinimum(-1000.0)
        self.calibrationBox_6_1.setMaximum(1000.0)
        self.calibrationBox_6_1.setObjectName(_fromUtf8("calibrationBox_6_1"))
        self.gridLayout_3.addWidget(self.calibrationBox_6_1, 5, 4, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.motorMaxSpeedBox = QtGui.QDoubleSpinBox(self.page)
        self.motorMaxSpeedBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.motorMaxSpeedBox.setDecimals(0)
        self.motorMaxSpeedBox.setMaximum(100000.0)
        self.motorMaxSpeedBox.setProperty("value", 400.0)
        self.motorMaxSpeedBox.setObjectName(_fromUtf8("motorMaxSpeedBox"))
        self.gridLayout_5.addWidget(self.motorMaxSpeedBox, 0, 1, 1, 1)
        self.motorMinPulseFreqBox = QtGui.QDoubleSpinBox(self.page)
        self.motorMinPulseFreqBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.motorMinPulseFreqBox.setDecimals(2)
        self.motorMinPulseFreqBox.setMaximum(100.0)
        self.motorMinPulseFreqBox.setProperty("value", 1.0)
        self.motorMinPulseFreqBox.setObjectName(_fromUtf8("motorMinPulseFreqBox"))
        self.gridLayout_5.addWidget(self.motorMinPulseFreqBox, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.page)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_5.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.page)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_5.addWidget(self.label_16, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.page)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_5.addWidget(self.label_17, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 3, 1, 1, 1)
        self.motorMaxPulseFreqBox = QtGui.QDoubleSpinBox(self.page)
        self.motorMaxPulseFreqBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.motorMaxPulseFreqBox.setDecimals(2)
        self.motorMaxPulseFreqBox.setMaximum(1000.0)
        self.motorMaxPulseFreqBox.setProperty("value", 5.0)
        self.motorMaxPulseFreqBox.setObjectName(_fromUtf8("motorMaxPulseFreqBox"))
        self.gridLayout_5.addWidget(self.motorMaxPulseFreqBox, 2, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 3, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 4, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_13 = QtGui.QLabel(self.page)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.rightStimEdit = QtGui.QLineEdit(self.page)
        self.rightStimEdit.setObjectName(_fromUtf8("rightStimEdit"))
        self.gridLayout_4.addWidget(self.rightStimEdit, 1, 1, 1, 1)
        self.leftStimEdit = QtGui.QLineEdit(self.page)
        self.leftStimEdit.setObjectName(_fromUtf8("leftStimEdit"))
        self.gridLayout_4.addWidget(self.leftStimEdit, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.page)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 2, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 1, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_14 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout.addWidget(self.label_14)
        self.loadCalibrationButton = QtGui.QPushButton(self.page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadCalibrationButton.sizePolicy().hasHeightForWidth())
        self.loadCalibrationButton.setSizePolicy(sizePolicy)
        self.loadCalibrationButton.setObjectName(_fromUtf8("loadCalibrationButton"))
        self.horizontalLayout.addWidget(self.loadCalibrationButton)
        self.gridLayout_6.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_6.addWidget(self.label_15, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 0, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(self.page)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 3, 1, 1)
        self.yForceEdit = QtGui.QLineEdit(self.page)
        self.yForceEdit.setObjectName(_fromUtf8("yForceEdit"))
        self.gridLayout_2.addWidget(self.yForceEdit, 2, 1, 1, 1)
        self.zForceEdit = QtGui.QLineEdit(self.page)
        self.zForceEdit.setObjectName(_fromUtf8("zForceEdit"))
        self.gridLayout_2.addWidget(self.zForceEdit, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.page)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.xForceEdit = QtGui.QLineEdit(self.page)
        self.xForceEdit.setObjectName(_fromUtf8("xForceEdit"))
        self.gridLayout_2.addWidget(self.xForceEdit, 1, 1, 1, 1)
        self.xTorqueEdit = QtGui.QLineEdit(self.page)
        self.xTorqueEdit.setObjectName(_fromUtf8("xTorqueEdit"))
        self.gridLayout_2.addWidget(self.xTorqueEdit, 1, 3, 1, 1)
        self.yTorqueEdit = QtGui.QLineEdit(self.page)
        self.yTorqueEdit.setObjectName(_fromUtf8("yTorqueEdit"))
        self.gridLayout_2.addWidget(self.yTorqueEdit, 2, 3, 1, 1)
        self.zTorqueEdit = QtGui.QLineEdit(self.page)
        self.zTorqueEdit.setObjectName(_fromUtf8("zTorqueEdit"))
        self.gridLayout_2.addWidget(self.zTorqueEdit, 3, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.page)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.page)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.page)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.page)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 3, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.stimulusTypeTab = QtGui.QTabWidget(self.page_2)
        self.stimulusTypeTab.setTabPosition(QtGui.QTabWidget.North)
        self.stimulusTypeTab.setObjectName(_fromUtf8("stimulusTypeTab"))
        self.sineTab = QtGui.QWidget()
        self.sineTab.setObjectName(_fromUtf8("sineTab"))
        self.gridLayout = QtGui.QGridLayout(self.sineTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.sineTab)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.sineTab)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 1, 0, 1, 1)
        self.bendFrequencyBox = QtGui.QDoubleSpinBox(self.sineTab)
        self.bendFrequencyBox.setDecimals(2)
        self.bendFrequencyBox.setSingleStep(0.1)
        self.bendFrequencyBox.setObjectName(_fromUtf8("bendFrequencyBox"))
        self.gridLayout.addWidget(self.bendFrequencyBox, 2, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
        self.bendAmplitudeBox = QtGui.QDoubleSpinBox(self.sineTab)
        self.bendAmplitudeBox.setDecimals(0)
        self.bendAmplitudeBox.setObjectName(_fromUtf8("bendAmplitudeBox"))
        self.gridLayout.addWidget(self.bendAmplitudeBox, 1, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.sineTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 0, 0, 1, 2)
        self.stimulusTypeTab.addTab(self.sineTab, _fromUtf8(""))
        self.freqSweepTab = QtGui.QWidget()
        self.freqSweepTab.setObjectName(_fromUtf8("freqSweepTab"))
        self.stimulusTypeTab.addTab(self.freqSweepTab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.stimulusTypeTab)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.backButton = QtGui.QPushButton(SetupDialog)
        self.backButton.setEnabled(False)
        self.backButton.setObjectName(_fromUtf8("backButton"))
        self.horizontalLayout_2.addWidget(self.backButton)
        self.nextButton = QtGui.QPushButton(SetupDialog)
        self.nextButton.setDefault(True)
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.horizontalLayout_2.addWidget(self.nextButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_13.setBuddy(self.rightStimEdit)
        self.label_12.setBuddy(self.leftStimEdit)
        self.label_5.setBuddy(self.xTorqueEdit)
        self.label_8.setBuddy(self.yForceEdit)
        self.label_9.setBuddy(self.zForceEdit)
        self.label_10.setBuddy(self.yTorqueEdit)
        self.label_11.setBuddy(self.zTorqueEdit)
        self.label_3.setBuddy(self.xForceEdit)

        self.retranslateUi(SetupDialog)
        self.stackedWidget.setCurrentIndex(1)
        self.stimulusTypeTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SetupDialog)
        SetupDialog.setTabOrder(self.xForceEdit, self.yForceEdit)
        SetupDialog.setTabOrder(self.yForceEdit, self.zForceEdit)
        SetupDialog.setTabOrder(self.zForceEdit, self.xTorqueEdit)
        SetupDialog.setTabOrder(self.xTorqueEdit, self.yTorqueEdit)
        SetupDialog.setTabOrder(self.yTorqueEdit, self.zTorqueEdit)
        SetupDialog.setTabOrder(self.zTorqueEdit, self.leftStimEdit)
        SetupDialog.setTabOrder(self.leftStimEdit, self.rightStimEdit)
        SetupDialog.setTabOrder(self.rightStimEdit, self.motorMaxSpeedBox)
        SetupDialog.setTabOrder(self.motorMaxSpeedBox, self.motorMinPulseFreqBox)
        SetupDialog.setTabOrder(self.motorMinPulseFreqBox, self.motorMaxPulseFreqBox)
        SetupDialog.setTabOrder(self.motorMaxPulseFreqBox, self.calibrationBox_1_1)
        SetupDialog.setTabOrder(self.calibrationBox_1_1, self.calibrationBox_1_2)
        SetupDialog.setTabOrder(self.calibrationBox_1_2, self.calibrationBox_1_3)
        SetupDialog.setTabOrder(self.calibrationBox_1_3, self.calibrationBox_1_4)
        SetupDialog.setTabOrder(self.calibrationBox_1_4, self.calibrationBox_1_5)
        SetupDialog.setTabOrder(self.calibrationBox_1_5, self.calibrationBox_1_6)
        SetupDialog.setTabOrder(self.calibrationBox_1_6, self.calibrationBox_2_1)
        SetupDialog.setTabOrder(self.calibrationBox_2_1, self.calibrationBox_2_2)
        SetupDialog.setTabOrder(self.calibrationBox_2_2, self.calibrationBox_2_3)
        SetupDialog.setTabOrder(self.calibrationBox_2_3, self.calibrationBox_2_4)
        SetupDialog.setTabOrder(self.calibrationBox_2_4, self.calibrationBox_2_5)
        SetupDialog.setTabOrder(self.calibrationBox_2_5, self.calibrationBox_2_6)
        SetupDialog.setTabOrder(self.calibrationBox_2_6, self.calibrationBox_3_1)
        SetupDialog.setTabOrder(self.calibrationBox_3_1, self.calibrationBox_3_2)
        SetupDialog.setTabOrder(self.calibrationBox_3_2, self.calibrationBox_3_3)
        SetupDialog.setTabOrder(self.calibrationBox_3_3, self.calibrationBox_3_4)
        SetupDialog.setTabOrder(self.calibrationBox_3_4, self.calibrationBox_3_5)
        SetupDialog.setTabOrder(self.calibrationBox_3_5, self.calibrationBox_3_6)
        SetupDialog.setTabOrder(self.calibrationBox_3_6, self.calibrationBox_4_1)
        SetupDialog.setTabOrder(self.calibrationBox_4_1, self.calibrationBox_4_2)
        SetupDialog.setTabOrder(self.calibrationBox_4_2, self.calibrationBox_4_3)
        SetupDialog.setTabOrder(self.calibrationBox_4_3, self.calibrationBox_4_4)
        SetupDialog.setTabOrder(self.calibrationBox_4_4, self.calibrationBox_4_5)
        SetupDialog.setTabOrder(self.calibrationBox_4_5, self.calibrationBox_4_6)
        SetupDialog.setTabOrder(self.calibrationBox_4_6, self.calibrationBox_5_1)
        SetupDialog.setTabOrder(self.calibrationBox_5_1, self.calibrationBox_5_2)
        SetupDialog.setTabOrder(self.calibrationBox_5_2, self.calibrationBox_5_3)
        SetupDialog.setTabOrder(self.calibrationBox_5_3, self.calibrationBox_5_4)
        SetupDialog.setTabOrder(self.calibrationBox_5_4, self.calibrationBox_5_5)
        SetupDialog.setTabOrder(self.calibrationBox_5_5, self.calibrationBox_5_6)
        SetupDialog.setTabOrder(self.calibrationBox_5_6, self.calibrationBox_6_1)
        SetupDialog.setTabOrder(self.calibrationBox_6_1, self.calibrationBox_6_2)
        SetupDialog.setTabOrder(self.calibrationBox_6_2, self.calibrationBox_6_3)
        SetupDialog.setTabOrder(self.calibrationBox_6_3, self.calibrationBox_6_4)
        SetupDialog.setTabOrder(self.calibrationBox_6_4, self.calibrationBox_6_5)
        SetupDialog.setTabOrder(self.calibrationBox_6_5, self.calibrationBox_6_6)

    def retranslateUi(self, SetupDialog):
        SetupDialog.setWindowTitle(_translate("SetupDialog", "Setup channels...", None))
        self.motorMaxSpeedBox.setSuffix(_translate("SetupDialog", "RPM", None))
        self.motorMinPulseFreqBox.setSuffix(_translate("SetupDialog", "kHz", None))
        self.label_18.setText(_translate("SetupDialog", "Max pulse frequency:", None))
        self.label_16.setText(_translate("SetupDialog", "Min pulse frequency:", None))
        self.label_17.setText(_translate("SetupDialog", "Maximum speed:", None))
        self.motorMaxPulseFreqBox.setSuffix(_translate("SetupDialog", "kHz", None))
        self.label_13.setText(_translate("SetupDialog", "Right stim:", None))
        self.label_12.setText(_translate("SetupDialog", "Left stim:", None))
        self.label_14.setText(_translate("SetupDialog", "Calibration matrix:", None))
        self.loadCalibrationButton.setText(_translate("SetupDialog", "Load...", None))
        self.label_15.setText(_translate("SetupDialog", "Motor parameters:", None))
        self.label.setText(_translate("SetupDialog", "Input channels:", None))
        self.label_2.setText(_translate("SetupDialog", "Output channels:", None))
        self.label_5.setText(_translate("SetupDialog", "X:", None))
        self.label_6.setText(_translate("SetupDialog", "Torque", None))
        self.label_7.setText(_translate("SetupDialog", "Force", None))
        self.label_8.setText(_translate("SetupDialog", "Y:", None))
        self.label_9.setText(_translate("SetupDialog", "Z:", None))
        self.label_10.setText(_translate("SetupDialog", "Y:", None))
        self.label_11.setText(_translate("SetupDialog", "Z:", None))
        self.label_3.setText(_translate("SetupDialog", "X:", None))
        self.label_4.setText(_translate("SetupDialog", "Stimulus type:", None))
        self.label_20.setText(_translate("SetupDialog", "Frequency:", None))
        self.label_19.setText(_translate("SetupDialog", "Amplitude:", None))
        self.bendFrequencyBox.setSuffix(_translate("SetupDialog", "Hz", None))
        self.bendAmplitudeBox.setSuffix(_translate("SetupDialog", "deg", None))
        self.label_21.setText(_translate("SetupDialog", "Bending", None))
        self.stimulusTypeTab.setTabText(self.stimulusTypeTab.indexOf(self.sineTab), _translate("SetupDialog", "Sine", None))
        self.stimulusTypeTab.setTabText(self.stimulusTypeTab.indexOf(self.freqSweepTab), _translate("SetupDialog", "Frequency Sweep", None))
        self.backButton.setText(_translate("SetupDialog", "Back", None))
        self.nextButton.setText(_translate("SetupDialog", "Next", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SetupDialog = QtGui.QDialog()
    ui = Ui_SetupDialog()
    ui.setupUi(SetupDialog)
    SetupDialog.show()
    sys.exit(app.exec_())

